### PR TITLE
[MINOR] correct document mistakes

### PR DESCRIPTION
**Pull request by FANNG1**
## Which issue does this PR close?
no

## What changes are included in this PR?
replace [`TableProvider]` with [`TableProvider`] in `catalog.rs`

## Are these changes tested?
no, just document changes.

## Are there any user-facing changes?
no

### CODE REVIEW

**Review by lewiszlw — APPROVED** [review]
Good catch. Thank you @FANNG1 .

**Comment by lewiszlw** [comment]
I think line 102 should be changed too.

**Comment by FANNG1** [comment]
> I think line 102 should be changed too.

updated, thanks for the view

**Review by jonahgao — APPROVED** [review]
Thanks @FANNG1

**Pull request merged**
