### PR TITLE
fix: enable DF's nested_expressions feature by in datafusion-substrait tests to make them pass

### LINKED ISSUE #13854: substrait_integration integration tests are failing
### Describe the bug

substrait_integration integration tests are failing

### To Reproduce

on main at 9f530dd1987d863dd4de99198df5b2c3e242bf6e
```shell
cargo test -p datafusion-substrait
```

Fails  like this:
```
failures:

---- cases::roundtrip_logical_plan::roundtrip_literal_list stdout ----
Error: Internal("Expected a simplified result, but none was found")

---- cases::roundtrip_logical_plan::roundtrip_values stdout ----
Error: Internal("Expected a simplified result, but none was found")


failures:
    cases::roundtrip_logical_plan::roundtrip_literal_list
    cases::roundtrip_logical_plan::roundtrip_values

test result: FAILED. 133 passed; 2 failed; 7 ignored; 0 measured; 0 filtered out; finished in 0.15s

error: test failed, to rerun pass `-p datafusion-substrait --test substrait_integration`
```

### Expected behavior

I expect
1.  the tests to pass
2. These tests are run as part of CI

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Blizzara**
## Which issue does this PR close?

Closes #13854

## Rationale for this change

https://github.com/apache/datafusion/pull/13594/files#diff-d195b6dfaaed44b9828e145dc50c075c77b7faf8f44783ca5e6eda2c617af928L39 removed DF default features from the substrait crate. That broke some tests that depended on stuff coming from nested_expressions feature. 

Interestingly, the tests still passed in CI but failed when run locally - maybe due to CI running a whole bunch of tests at once and thus compiling DF with different set of features, or something?

## Are there any user-facing changes?

No - but in the original PR that caused the issue, that _might_ be a breaking change to some consumer if someone has disabled default_features for DF but things have been working still because datafusion-substrait has been pulling those features in anyways. Not sure if that can happen - I checked our internal stuff and that seems to work fine against a recent commit on main.

### CODE REVIEW

**Comment by Blizzara** [comment]
Fyi @alamb

**Comment by alamb** [comment]
> Interestingly, the tests still passed in CI but failed when run locally - maybe due to CI running a whole bunch of tests at once and thus compiling DF with different set of features, or something?

Yeah I think they are run like this
https://github.com/apache/datafusion/blob/079f6219fed8eb8812b028257c031dfdfba96cb4/.github/workflows/rust.yml#L160C1-L161C1

**Review by alamb — APPROVED** [review]
Thanks @Blizzara -- I verified this works locally for me too.

It is annoying that CI didn't catch this but I also think it might be too much effort / overhead to add a specific ci check for each sub package.If it happens again we can maybe add some more tests

**Comment by alamb** [comment]
Thank you very much @Blizzara -- great 🕵️ 

I also filed a follow up ticket to make the error message more helpful
-  https://github.com/apache/datafusion/pull/13859

**Pull request merged**
