### PR TITLE
Minor: change the sort merge join emission as incremental

### PR DESCRIPTION
**Pull request by berkaysynnada**
## Which issue does this PR close?

Closes #.

## Rationale for this change

Since SortMergeJoin appears only when the inputs are sorted, marking its emission type as incremental would reflect its behavior better.

### CODE REVIEW

**Review by ozankabak — APPROVED** [review]
LGTM - this is a bugfix as SMJ always emits incrementally

**Comment by alamb** [comment]
I wonder if there is some way / reason to test this (I realize it just a property, I was worried it might be broken in the future)

**Comment by berkaysynnada** [comment]
> I wonder if there is some way / reason to test this (I realize it just a property, I was worried it might be broken in the future)

AFAIK SMJ is not very stable and it is getting update frequently. Once it becomes stabilized, then it will be more meaningful to assign a property based on a more comprehensive analysis (perhaps it may behave like both incremental and final)

**Comment by alamb** [comment]
> > I wonder if there is some way / reason to test this (I realize it just a property, I was worried it might be broken in the future)
> 
> AFAIK SMJ is not very stable and it is getting update frequently. Once it becomes stabilized, then it will be more meaningful to assign a property based on a more comprehensive analysis (perhaps it may behave like both incremental and final)

Maybe we can figure out how to write a test that mimics whatever you are doing with these properties (e.g. run a plan end to end that requires the plan to emit data incrementally or something) 🤔

**Pull request merged**
