### PR TITLE
Support `DictionaryArray` in `OVER` clause 

### LINKED ISSUE #13151: Range queries on Dictionary data types are not implemented
### Describe the bug

`select dense_rank() over (order by arrow_cast('abc', 'Utf8'));` works but `select dense_rank() over (order by arrow_cast('abc', 'Dictionary(UInt16, Utf8)'));` does not and fails with:

```
Internal error: Cannot run range queries on datatype: Dictionary(UInt16, Utf8).
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

### To Reproduce

Run the above in `datafusion-cli`

### Expected behavior

All operations are implemented for dictionary encoded columns

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by adriangb**
Fixes #13151

### CODE REVIEW

**Comment by adriangb** [comment]
I tested this manually with datafusion-cli. Happy to add a test if needed but maybe it's okay as is.

**Comment by adriangb** [comment]
cc @alamb

**Comment by findepi** [comment]
It looks like a new & cool capability. Is it possible to add a test?

**Comment by adriangb** [comment]
More like existing functionality that wasn't enabled.

Any suggestions as to where I should add said test?

**Comment by alamb** [comment]
I tried to produce an error / write some examples in dictionary.slt and I couldn't figure out how to trigger an issue

```
(venv) andrewlamb@Andrews-MacBook-Pro-2:~/Software/datafusion$ git diff
diff --git a/datafusion/sqllogictest/test_files/dictionary.slt b/datafusion/sqllogictest/test_files/dictionary.slt
index 176331f57..e802ddfe6 100644
--- a/datafusion/sqllogictest/test_files/dictionary.slt
+++ b/datafusion/sqllogictest/test_files/dictionary.slt
@@ -320,6 +320,41 @@ ORDER BY
 2023-12-20T01:30:00 1000 f1 32.0
 2023-12-20T01:30:00 1000 f2 foo

+# Window Functions
+query TTTT
+SELECT "tag_id", "type",
+  lead("type") OVER (PARTITION BY "tag_id" ORDER BY "time") as "next_type",
+  lag("type") OVER (PARTITION BY "tag_id" ORDER BY "time") as "last_type"
+FROM m2;
+----
+1000 active active NULL
+1000 active active active
+1000 active active active
+1000 active active active
+1000 active active active
+1000 active passive active
+1000 passive passive active
+1000 passive passive passive
+1000 passive passive passive
+1000 passive NULL passive
+
+query TTTT
+SELECT "tag_id", "type",
+  lead("type") OVER (PARTITION BY "tag_id" ORDER BY "time"  RANGE BETWEEN 2 PRECEDING AND CURRENT ROW) as "next_type",
+  lag("type") OVER (PARTITION BY "tag_id" ORDER BY "time") as "last_type"
+FROM m2;
+----
+1000 active active NULL
+1000 active active active
+1000 active active active
+1000 active active active
+1000 active active active
+1000 active passive active
+1000 passive passive active
+1000 passive passive passive
+1000 passive passive passive
+1000 passive NULL passive
+
```

**Comment by alamb** [comment]
I am concerned that the lack of testing here would mean we could accidentally break the behavior without knowing it in some future refactor

**Comment by alamb** [comment]
Oh, now I see there is an example in https://github.com/apache/datafusion/issues/13151#issue-2619921370

Maybe we can just add that example to dictionary.slt and we'll be good?

**Comment by adriangb** [comment]
I have no experience with these `slt` files but I'll give it a shot!

**Comment by adriangb** [comment]
@alamb is 359721f right?

**Comment by adriangb** [comment]
Guess we'll find out soon 😆

**Comment by adriangb** [comment]
@alamb looks like that worked 🚀

**Comment by alamb** [comment]
> @alamb is [359721f](https://github.com/apache/datafusion/commit/359721f7b6fd864389900463b5813686770e103b) right?

BTW I normally run this like `cargo test --test sqllogictests -- window --complete` and it will fill in the correct results

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @adriangb

**Pull request merged**
