### PR TITLE
chore: Improve performance of Parquet statistics conversion

### PR DESCRIPTION
**Pull request by Weijun-H**
## Which issue does this PR close?

Closes #.

## Rationale for this change

Refactor the code `get_statistics!` in `statistics.rs` to improve the performance of converting Parquet statistics to Arrow arrays. Instead of using conditional checks and `try_from` conversions, use the `ok()` method to handle the conversion and filtering of values. This change simplifies the code and improves readability.

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thanks @Weijun-H  -- I think this is a nice code impeovement ❤️ 

I am not sure this will improve the performance -- but you could run the benchmarks if you wanted to measure (`cargo bench --bench parquet_statistic`)

I filed https://github.com/apache/datafusion/issues/10934 to track adding a benchmark for data pages

**Comment by alamb** [comment]
cc @xinlifoobar and @marvinlanhenke

**Comment by marvinlanhenke** [comment]
> I think this is a nice code impeovement ❤️

It is indeed. Thanks @Weijun-H really nice refactor.

> I am not sure this will improve the performance

I'll guess in terms of performance it won't make any difference. 
However, it is more readable and thats always great, so thanks again.

**Review by xinlifoobar — APPROVED** [review]
Great refactor, thanks :)

**Review by marvinlanhenke — APPROVED** [review]

**Comment by alamb** [comment]
Thanks again everyone

**Pull request merged**
