### PR TITLE
Add distinct aggregate tests to sqllogictest

### LINKED ISSUE #2408: `avg(distinct)` support
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

DataFusion does not `avg(distinct ..)`:

```sql
> select avg(distinct a), avg(distinct b) from values(1, 2) t(a, b);
Execution error: avg(DISTINCT) aggregations are not available
```

Somewhat confusingly DataFusion does appear to support a single distinct `avg` 

```
> select avg(distinct a) from values(1, 2) t(a, b);
+-------------------+
| avg(DISTINCT t.a) |
+-------------------+
| 1.0               |
+-------------------+
1 row(s) fetched.
Elapsed 0.015 seconds.
```

But it does this by rewriting effectively rewriting the query `select avg(distinct a) ` to `select avg(a) from (select distinct a ...)` in the SingleDistinctToGroupBy rule

**Describe the solution you'd like**
Support multile distinct avg aggregates:
https://github.com/apache/datafusion/blob/2d303346c7d44a78d317e7b7b959cbd94edfb891/datafusion/functions-aggregate/src/average.rs#L116-L118

**Describe alternatives you've considered**
Basically we could follow the model of `COUNT(distinct ...)` aggregates:

In this case, there is a separate accumulator type that is implemented for count distinct

https://github.com/apache/datafusion/blob/5d08325165c1a7b32e5e35164919e83d46735e98/datafusion/functions-aggregate/src/count.rs#L234-L233

**Additional context**

### LINKED ISSUE #2410: var(distinct) support
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
complete description later.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### LINKED ISSUE #2411: `median(distinct)` support
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Jefffrey**
## Which issue does this PR close?

Relates to #2411, #2410, #2408

## Rationale for this change

Datafusion already supports these use cases. Just locking them into the test suite

### CODE REVIEW

**Review by jayzhan211 — APPROVED** [review]
👍

**Comment by Jefffrey** [comment]
FYI we don't support this

```
> select median(distinct "1"), median("1") from '/home/jeffrey/Downloads/data.csv';
This feature is not implemented: MEDIAN(DISTINCT) aggregations are not available
```

But maybe can tackle as separate issue from those original issues :thinking:

**Comment by Weijun-H** [comment]
> FYI we don't support this
> 
> ```
> > select median(distinct "1"), median("1") from '/home/jeffrey/Downloads/data.csv';
> This feature is not implemented: MEDIAN(DISTINCT) aggregations are not available
> ```
> 
> But maybe can tackle as separate issue from those original issues 🤔
> 
> See [#10159 (comment)](https://github.com/apache/datafusion/issues/10159#issuecomment-2067873654)

If it hasn't been implemented yet, we should add them to sqllogictest and return an error first.

**Comment by Jefffrey** [comment]
Done. Also I'll keep the original issues open.

**Review by Weijun-H — APPROVED** [review]
LGTM! Thanks @Jefffrey

**Comment by alamb** [comment]
Thanks @Jefffrey  and @Weijun-H and @jayzhan211  🚀

**Pull request merged**
