### PR TITLE
doc-gen: migrate scalar functions (datetime) documentation 1/2

### PR DESCRIPTION
**Pull request by Chen-Yuan-Lai**
## Which issue does this PR close?

Closes #13671 .

## What changes are included in this PR?

As discussed in #13671 , this PR will migrate the parts of builtin datetime functions documentation that currently support migration.

### CODE REVIEW

**Comment by jonahgao** [comment]
This PR has 1 failing CI check that needs to be fixed

**Comment by Chen-Yuan-Lai** [comment]
@jonahgao I found similar CI check failures in other PRs - I'll fix them all together. Thanks for reviewing 🙏

**Review by Omega359 — APPROVED** [review]
lgtm

**Review by alamb — APPROVED** [review]
Thank you @Chen-Yuan-Lai  and @Omega359 🙏

**Pull request merged**
