### PR TITLE
refactor: add `get_available_parallelism` function

### LINKED ISSUE #13591: Move available_parallelism() into utility function
### Is your feature request related to a problem or challenge?

As noted by @comphead in  https://github.com/apache/datafusion/pull/13579#pullrequestreview-2465606280
We can move the repeated:
```
available_parallelism()
             .unwrap_or(NonZero::new(1).unwrap())
             .get()
```
into a seperate method.

### Describe the solution you'd like

Create a utility method and replace all calls to `std:thread::available_parallelism` with this new method.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alan910127**
## Which issue does this PR close?

Closes #13591.

## Rationale for this change

In https://github.com/apache/datafusion/pull/13579#pullrequestreview-2465606280, it was suggested that the repeated use of `std::thread::available_parallelism` with  fallback logic could be refactored for clarity and to reduce duplication. Extracting this logic into a utility function improves code readability and reduces the likelihood of errors.

## What changes are included in this PR?

This PR introduces a new utility function:

```rust
pub fn get_available_parallelism() -> usize;
```

It replaces the following repeated code snippet:

```rust
std::thread::available_parallelism().unwrap_or(NonNull::new(1).unwrap()).get()
```

with a call to the new function:

```rust
get_available_parallelism()
```

## Are these changes tested?

No tests are added for this change as it is a straightforward refactor of existing functionality. However, if reviewers feel this requires testing, I am happy to add them.

## Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by findepi** [comment]
The [clippy](https://github.com/apache/datafusion/actions/runs/12073608931/job/33672780242?pr=13595#logs) job failed. This is probably nothing wrong with this PR, see https://github.com/apache/datafusion/issues/13597.

**Review by comphead — COMMENTED** [review]
Thanks @alan910127 for your first contribution. 
Please take care on clippy. I feel the PR is good.

**Comment by alan910127** [comment]
Hi @comphead, Thanks for your review! I just checked the pipeline logs, the clippy errors are not related to my changes. Perhaps it's what @findepi mentioned in the previous comment.

**Comment by comphead** [comment]
@alan910127 please rebase from the latest main

**Comment by alan910127** [comment]
@comphead Rebased.

**Review by comphead — APPROVED** [review]
lgtm thanks @alan910127

**Comment by comphead** [comment]
Since this is a first time contribution I'll be waiting for another review before merging it in

**Review by jonahgao — APPROVED** [review]
LGTM, thanks @alan910127 . I merged main, so that this PR can be checked by the new version of clippy.

**Pull request merged**
