### PR TITLE
Merge `string-view2` branch: reading from parquet up to 2x faster for some ClickBench queries  (not on by default)

### PR DESCRIPTION
**Pull request by alamb**
~Draft until arrow `52.2.0` is released to crates.io (expected Sat July 27)~

## Which issue does this PR close?
Part of https://github.com/apache/datafusion/issues/10918

Closes https://github.com/apache/datafusion/issues/10921

* Note 1: this code has been previously reviewed
* Note 2: The feature isn't on by default (yet) until https://github.com/apache/datafusion/issues/11682

## Rationale for this change

We have been integrating a set of StringView changes on the [`string-view2`](https://github.com/apache/datafusion/tree/string-view2) branch as they rely on un-released code in arrow-rs . Once those changes are released and DataFusion uses them we can bring this code directly to main. 

## What changes are included in this PR?

* Add a config to force using string view in benchmark (#11514) - @XiangpengHao
* Add String view helper functions (#11517)  - @XiangpengHao
* Add ArrowBytesViewMap and ArrowBytesViewSet (#11515) - @XiangpengHao
* Enable GroupValueBytesView for aggregation with StringView types (#…  - @XiangpengHao
* Initial support for regex_replace on StringViewArray (#11556) - @XiangpengHao
* Add support for Utf8View for date/temporal codepaths (#11518)  - @a10y
* GC StringViewArray in CoalesceBatchesStream (#11587) - @XiangpengHao
* [Bug] fix bug in return type inference of utf8_to_int_type (#11662) 
* Increase ByteViewMap block size to 2MB (#11674)  - @XiangpengHao
* Change --string-view to only apply to parquet formats (#11663) - @XiangpengHao
* Implement native support StringView for character length (#11676) - @XiangpengHao

## Are these changes tested?
CI

## Are there any user-facing changes?

When StringView is enabled, benchmarks run significantly faster

### CODE REVIEW

**Comment by alamb** [comment]
CI appears to be failing due to https://github.com/apache/datafusion/issues/11671

**Comment by alamb** [comment]
Update here is that we are on track to release arrow `52.2.0` to crates.io tomorrow Saturday July 28. (thank you to @waynexia  @viirya @wjones127 for verifying / voting 🙏 ).

Then we'll need a PR to update datafusion to arrow 52.2.0 (which should be straightforward)

Then I will change this PR to ready to review and we should be able to merge it into DataFusion main

🤞

**Comment by alamb** [comment]
This PR is now ready for review (mostly I am hoping another committer will approve/merge it as I can't approve my own PR)

**Review by Dandandan — APPROVED** [review]
🚀

**Comment by alamb** [comment]
Thanks @Dandandan  -- so exciting!

I plan to work with @XiangpengHao  and figure out what we need to do to get this feature on by default

**Comment by alamb** [comment]
🚀

**Pull request merged**
