### PR TITLE
Make statistics_from_parquet_meta a sync function

### PR DESCRIPTION
**Pull request by adriangb**
It seems like this function doesn't need to be async. I exposed a sync version and deprecated the async one.

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thanks @adriangb  -- I took the liberty of merging up from main and fixing a clippy issue on this PR to get CI to pass

**Comment by adriangb** [comment]
Thanks!

**Comment by alamb** [comment]
Thanks again

**Comment by adriangb** [comment]
Thank you for looking at this Andrew. I found this while poking around looking for encoding/decoding functionality for parquet metadata. I had some questions I posted here: https://github.com/apache/arrow-rs/discussions/5988. Would you mind taking a look if you have a minute?

**Pull request merged**
