### PR TITLE
chore: Rename UserDefinedSQLPlanner to ExprPlanner

### PR DESCRIPTION
**Pull request by andygrove**
## Which issue does this PR close?

Closes https://github.com/apache/datafusion/issues/11304

### CODE REVIEW

**Comment by andygrove** [comment]
@alamb @samuelcolvin fyi

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @andygrove 

I merged up from main and also fixed a clippy error to try and help get this PR mergeable

**Comment by alamb** [comment]
merging up to resolve a conflict...

**Review by samuelcolvin — APPROVED** [review]
Lgtm, thank you so much.

**Pull request merged**
