### PR TITLE
Convert Correlation to UDAF

### LINKED ISSUE #10884: Convert `Correlation` to UDAF
### Is your feature request related to a problem or challenge?

Similar to other issues in #8708  Move `datafusion/physical-expr/src/aggregate/correlation.rs` to `datafusion/functions-aggregate/src/correlation.rs`

I found `CovarianceAccumulator` in `datafusion/physical-expr/src/aggregate/covariance.rs` is not removed, we should remove it and use the one in `datafusion/functions-aggregate/src/covariance.rs` instead. The same with `StddevAccumulator`

### Describe the solution you'd like

_No response_

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pingsutw**
## Which issue does this PR close?

Closes #10884

## Rationale for this change
We are moving aggregate functions out of the core to ensure the core APIs are sufficient to implement all aggregates and make datafusion more configurable

### CODE REVIEW

**Comment by pingsutw** [comment]
@jayzhan211 Mind taking a quick look? I'm a new contributor, so I might miss something.

**Review by jayzhan211 — APPROVED** [review]
It looks pretty nice!

**Review by alamb — APPROVED** [review]
Thank you @pingsutw  and @jayzhan211 for the review

I took the liberty of merging this branch up from main to resolve some conflicts

**Comment by jayzhan211** [comment]
Thanks @alamb and @pingsutw

**Comment by pingsutw** [comment]
Thank you all!

**Pull request merged**
