### PR TITLE
`datafusion.catalog.has_headers` default value set to `true`

### LINKED ISSUE #11848: CSV headers not recognized
### Describe the bug

Giving a new try to `datafusion-cli`, I followed the first examples in documentation [Local Files/Directories](https://datafusion.apache.org/user-guide/cli/datasources.html):
```
$ echo "a,b" > data.csv
$ echo "1,2" >> data.csv
```
then
```
> datafusion-cli.exe
DataFusion CLI v40.0.0
> select * from './data.csv';
+----------+----------+
| column_1 | column_2 |
+----------+----------+
| a        | b        |
| 1        | 2        |
+----------+----------+
2 row(s) fetched.
```

I thought the mistake was due to Windows default settings (I set EOL as '\n' without success), then installed `datafusion-cli 40.0.0` on WSL with same results. Loading from a directory gave the same results:

```
> datafusion-cli.exe
DataFusion CLI v40.0.0
> select * from './data_dir/';
+----------+----------+
| column_1 | column_2 |
+----------+----------+
| a        | b        |
| 1        | 2        |
| a        | b        |
| 3        | 4        |
+----------+----------+
4 row(s) fetched.
```

### To Reproduce

see above

### Expected behavior

a and b should be headers. Maybe headers could be a defaulted option only.

### Additional context

_No response_

### LINKED ISSUE #11936: Change default value of `datafusion.catalog.has_header` to `true`
### Is your feature request related to a problem or challenge?

As @jgranduel  notes in  https://github.com/apache/datafusion/issues/11848

I think most people would expect when reading this data as a csv file, we would get two columns `a` and `b`

```csv
a,b
1,2
```

However, datafusion currently treats the CSV file as "without header" by default resulting in 

```
> datafusion-cli.exe
DataFusion CLI v40.0.0
> select * from './data_dir/';
+----------+----------+
| column_1 | column_2 |
+----------+----------+
| a        | b        |
| 1        | 2        |
+----------+----------+
4 row(s) fetched.
```

### Describe the solution you'd like

I propose removing this "rough edge" and changing the datafusion default behavior to be what I think most people would expect

```sql
+---+---+
| a | b |
+---+---+
| 1 | 2 |
+---+---+
```

### Describe alternatives you've considered

I think we should change the default vale of `datafusion.catalog.has_header` from `false` to `true`

https://github.com/apache/datafusion/blob/79fa6f9098be9a6e5b269cd3642694765b230ff1/datafusion/common/src/config.rs#L184-L186

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by korowa**
## Which issue does this PR close?

Closes #11848.
Closes #11936.

## Rationale for this change

Making `datafusion.catalog.has_headers` consistent with default `CsvReadOptions` / `WriterBuilder` has_header values.

## What changes are included in this PR?

- Default value for `datafusion.catalog.has_header` changed to True
- Fixed catalog.has_header value inheritance in case of writing to csv files (e.g. `insert` statements)

## Are these changes tested?

Covered by existing tests

## Are there any user-facing changes?

Statements involving external CSV tables now write / try to read header row as a default behavior.

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thank you @korowa 

Something we could consider is changing the default "has header" value in the configuration setting to be `true` as this is what I think most people would expect. I filed a ticket to propose doing so here https://github.com/apache/datafusion/issues/11936

**Comment by korowa** [comment]
It's in draft since I'm going to check if changing default value of `datafusion.catalog.has_header` will go smooth enough, and this PR can be replaced with default value change.

**Review by alamb — APPROVED** [review]
Thank you @korowa  - I think this is a great step forward in usability personally. 

Perhaps you can try to merge this PR yourself as a test of having the committer configuration setup correctly 🤔

**Comment by alamb** [comment]
Marking the PR as API change to get it some addtional visibility in documentation

**Comment by alamb** [comment]
🚀

**Pull request merged**
