### PR TITLE
Update to `clap` 4.5.16

### PR DESCRIPTION
**Pull request by findepi**

### CODE REVIEW

**Comment by alamb** [comment]
I think you can fix the CI failure by running `cargo fmt` in the `datafusion-cli` directory. eg.

```shell
cd datafusion-cli
cargo fmt
```

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @findepi

**Comment by findepi** [comment]
> I think you can fix the CI failure by running `cargo fmt` in the `datafusion-cli` directory

yep, sorry missed that.
fixed (& sorry for rebase)

**Comment by alamb** [comment]
🚀

**Pull request merged**
