### PR TITLE
Migrate testing optimizer rules to use `rewrite` API

### PR DESCRIPTION
**Pull request by lewiszlw**
## Which issue does this PR close?

part of https://github.com/apache/datafusion/issues/9637.

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thank you (again) @lewiszlw  -- this looks great.

I wonder if it is time to `deprecate` `OptimizerRule::try_optimize`

**Comment by lewiszlw** [comment]
The `CommonSubexprEliminate` rule has not been migrated yet.

**Comment by alamb** [comment]
> The `CommonSubexprEliminate` rule has not been migrated yet.

That is a good point -- though we could do something like `#[allow(deprecated)]` until it is. I hope to work on it over the next week or two

**Comment by alamb** [comment]
Thanks again @lewiszlw

**Pull request merged**
