### PR TITLE
Split the GroupColumn Implementations into smaller modules

### LINKED ISSUE #13262: Reorganize the GroupColumn implementations into more coherent modules
### Is your feature request related to a problem or challenge?

While reviewing https://github.com/apache/datafusion/pull/12996 I noticed that all the implementations of `GroupColumn` for different types were in [`datafusion/physical-plan/src/aggregates/group_values/group_column.rs`](https://github.com/apache/datafusion/blob/main/datafusion/physical-plan/src/aggregates/group_values/group_column.rs) which is:
1. a single large file
2. Not obvious that it is like an implementation  detail of `GroupValuesColumn`: https://github.com/apache/datafusion/blob/main/datafusion/physical-plan/src/aggregates/group_values/column.rs#L94-L93

### Describe the solution you'd like

I would like to propose rearrainging the code: 
1. Rename https://github.com/apache/datafusion/blob/main/datafusion/physical-plan/src/aggregates/group_values/column.rs to https://github.com/apache/datafusion/blob/main/datafusion/physical-plan/src/aggregates/group_values/multi_column/mod.rs
2. Move the implementations in datafusion/physical-plan/src/aggregates/group_values/group_column.rs to different modules within https://github.com/apache/datafusion/blob/main/datafusion/physical-plan/src/aggregates/group_values/multi_column (like `primitive.rs`, `bytes.rs`, etc)

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jiashenC**
## Which issue does this PR close?

Closes #13262.

## What changes are included in this PR?

* Introduce a new sub-directory: multi_column under group_value.
* Rename `column.rs`.
* Move implementation in `group_column.rs` to `primitive.rs`, `bytes.rs`, and `bytes_view.rs`. 

## Are these changes tested?

Using original tests.

## Are there any user-facing changes?

No

### CODE REVIEW

**Comment by jiashenC** [comment]
@alamb Can you please take a look at this PR? Thanks!

**Review by jonathanc-n — APPROVED** [review]
This lgtm! Thanks @jiashenC. After this gets merged we can maybe open a pr for #13263

**Review by alamb — APPROVED** [review]
This looks great -- thank you @jiashenC and @jonathanc-n

**Comment by alamb** [comment]
> @alamb Can you please take a look at this PR? Thanks!

Thank you very much for this PR -- I am sorry for the delay in reviewing (I was away for a few days).

**Review by alamb — APPROVED** [review]
Thank you @jiashenC  and @jonathanc-n  -- this looks great to me

**Pull request merged**
