### PR TITLE
minor: Remove docs archive

### PR DESCRIPTION
**Pull request by andygrove**
## Which issue does this PR close?

N/A

## Rationale for this change

I seem to have accidentally checked in a docs.tgz in https://github.com/apache/datafusion/pull/10407

### CODE REVIEW

**Comment by andygrove** [comment]
I suppose we need to look at removing this from the history as well

**Review by alamb — APPROVED** [review]
Let's at least get rid of it from main. 

It would be great to rewrite some commits on master to remove this file from the repo too (only the commits since https://github.com/apache/datafusion/pull/10407)

Maybe we can experiment with doing that on a branch and if it looks good we can force push that branch to main

**Comment by andygrove** [comment]
I removed it from branch-38 too

**Comment by alamb** [comment]
Filed https://github.com/apache/datafusion/issues/10422 to track potentially removing it from the repo history

**Pull request merged**
