### PR TITLE
[docs]: added `alternative_syntax` function for docs

### LINKED ISSUE #13139: feat: Add `alternative_syntax` function for docs
### Is your feature request related to a problem or challenge?

This is mentioned in #12741 from @Omega359. The doc migration is almost wrapped up, but there are a few functions that are listed in #12741 that have alternative syntax options.

### Describe the solution you'd like

Add an `alternative_syntax` to the docs.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jonathanc-n**
## Which issue does this PR close?

Closes #13139 .

## Rationale for this change
Added alternative syntax argument for doc functions

### CODE REVIEW

**Comment by jonathanc-n** [comment]
@Omega359 Does this seem fine?

**Comment by Omega359** [comment]
:heart: I like this! One minor suggestion: I would suggest changing the style of the alternate syntax to match the .with_syntax_example() style

**Comment by Omega359** [comment]
> ❤️ I like this! One minor suggestion: I would suggest changing the style of the alternate syntax to match the .with_syntax_example() style

Actually, on a second look, maybe we should just add the sql to the syntax example. Something for another issue, very minor.

**Review by alamb — APPROVED** [review]
THank you @jonathanc-n  and @Omega359

**Pull request merged**
