### PR TITLE
Move create_physical_expr to phy-expr-common #3

### LINKED ISSUE #10074: Move `create_physical_expr` to `physical-expr-common`
### Is your feature request related to a problem or challenge?

https://github.com/apache/arrow-datafusion/blob/671cef85c550969ab2c86d644968a048cb181c0c/datafusion/functions-aggregate/src/first_last.rs#L102-L117

I found that we need to match `Alias` cases,  it seems we should try to reuse `create_physical_sort_exprs` if possible

We need to move `create_physical_expr` to `physical-expr-common`, and this might involve moving lots of things to physical-expr-common` too, not sure if it is reasonable yet.

### Describe the solution you'd like

Two places that we need `create_physical_expr`
1. Convert to physical-expr in `accumulator` with `create_physical_sort_exprs`.
2. `reverse_expr`, convert logical aggr expr to physical aggr expr with `create_physical_expr`, given `AggregateFunction` expect to get `Arc<dyn AggregateExpr>`

### Describe alternatives you've considered

~Actually, we have what we need of physical sorting expression `ordering_req` in `AggregateFunctionExpr` already.
 But since `AccumulatorArgs` and `AggregateUDFImpl` live in `datafusion_expr` layer, so we can't get the value from it.~

~I still think it would be nice to have a design that can deal with physical-expr for UDAF 😞 
Should we move `AggregateUDFImpl` to a crate that imports both `datafusion-expr` and `datafusion-physical-expr-common`?~ 🤔 

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jayzhan211**
## Which issue does this PR close?

Closes #10176
Closes #10074
Closes #10144 

All in one in this PR.

### CODE REVIEW

**Comment by alamb** [comment]
Hi @jayzhan211  -- if we merge this one, does it close https://github.com/apache/datafusion/pull/10176  and https://github.com/apache/datafusion/pull/10144 ?

**Comment by jayzhan211** [comment]
> Hi @jayzhan211 -- if we merge this one, does it close #10176 and #10144 ?

Yes!

**Comment by alamb** [comment]
Sorry for being dense -- would you like me to review this PR? Or do you think we should review  (and merge) https://github.com/apache/datafusion/pull/10176 and https://github.com/apache/datafusion/pull/10144 first?

**Comment by jayzhan211** [comment]
It depends on you and other reviewers, if this PR is too large, we can close #1 first, and move on to #2 and finally this one.

**Review by alamb — COMMENTED** [review]
Thank you for this @jayzhan211 

I spent some time reviewing this PR this morining

One thing I am missing is the big picture description / story of "what code belongs in what crate". I suspect there is a good story here but I can't quite figure it out. 

In this case, I think getting the larger story straight will help avoid churn / code moving back and forth unecessairly. The larger story is also likely the key to understanding the end state.

## `create_physical_expr`

As I understand it, this PR is part of the larger quest to move aggregate functions out of datafusion-physical-expr #8708 

In my mind, `create_physical_expr` is a big switch statement between `Expr` --> `Arc<dyn PhysicalExpr>`

Once we have created a `Arc<dyn PhysicalExpr>` I don't really understand how/why we would ever get an `Expr` that we need to convert back to `Arc<dyn PhysicalExpr>` again.


## End state of dependencies??

Is the eventual plan to have something like the following? If so, I don't understand why the `functions-aggregates` needs to depends on `create_physical_erxpr`

```mermaid
  graph TD;
      functions-aggregates-->physical-expr-common;
      physical-expr-->physical-expr-common;
      core-->functions-aggregates;
      core-->physical-expr;
```

**Comment by alamb** [comment]
Here is another suggestion: https://github.com/apache/datafusion/issues/10074#issuecomment-2077439515

**Comment by jayzhan211** [comment]
> Once we have created a Arc<dyn PhysicalExpr> I don't really understand how/why we would ever get an Expr that we need to convert back to Arc<dyn PhysicalExpr> again.

I think we don't have any need to convert physical expr back to expr. But, we need to convert expr to physical-expr, because `accumulator` and `reverse_expr` are the functions that need `ordering_req: Vec<PhysicalSortExpr>`.

**Comment by jayzhan211** [comment]
If we can move `reverse_expr` related logic all to logical layer.... 🤔

**Pull request closed without merging**
