### PR TITLE
backport-to-DF-42: Provide field and schema metadata missing on distinct aggregations

### PR DESCRIPTION
**Pull request by Xuanwo**
Part of https://github.com/apache/datafusion/issues/12813

## Rationale for this change

This PR is used to backport #12691 to DF 42.

## What changes are included in this PR?

PR #12691

## Are these changes tested?

Yes, on main branch.

### CODE REVIEW

**Comment by Xuanwo** [comment]
cc @alamb and @matthewmturner for a look, thank you.

**Comment by alamb** [comment]
I believe CI will pass once we merge https://github.com/apache/datafusion/pull/12977 in. I will try and manage the PRs over the next few hours

**Comment by alamb** [comment]
Thank you @Xuanwo

**Comment by alamb** [comment]
close/reopen to trigger CI

**Review by alamb — APPROVED** [review]
Thanks @Xuanwo and @matthewmturner

**Comment by alamb** [comment]
I merged up from the `branch-42` to resolve a conflict

**Pull request merged**
