### PR TITLE
Migrate documentation for Aggregate Functions to code

### LINKED ISSUE #12827: Migrate documentation for aggregate functions from aggregate_functions.md to code
### Is your feature request related to a problem or challenge?

As part of https://github.com/apache/datafusion/issues/12740 this ticket is to migrate all the existing documentation for aggregate functions from the static file to code and to remove them from the static file. 

Here is the current static content:
* doc source: https://github.com/apache/datafusion/blob/main/docs/source/user-guide/sql/aggregate_functions.md
* rendered: https://datafusion.apache.org/user-guide/sql/aggregate_functions.html
* Code source: https://github.com/apache/datafusion/tree/main/datafusion/functions-aggregate/src

Need Functions:

- [ ] Port / Add `Documentation` for ApproxDistinct
- [ ] Port / Add `Documentation` for ApproxMedian
- [ ] Port / Add `Documentation` for ApproxPercentileCont
- [ ] Port / Add `Documentation` for ApproxPercentileContWithWeight
- [ ] Port / Add `Documentation` for ArrayAgg
- [ ] Port / Add `Documentation` for Avg
- [ ] Port / Add `Documentation` for BoolAnd
- [ ] Port / Add `Documentation` for BoolOr
- [ ] Port / Add `Documentation` for Correlation
- [ ] Port / Add `Documentation` for Count
- [ ] Port / Add `Documentation` for CovarianceSample
- [ ] Port / Add `Documentation` for CovariancePopulation
- [ ] Port / Add `Documentation` for FirstValue
- [ ] Port / Add `Documentation` for LastValue
- [ ] Port / Add `Documentation` for Grouping
- [ ] Port / Add `Documentation` for Median
- [ ] Port / Add `Documentation` for Max
- [ ] Port / Add `Documentation` for Min
- [ ] Port / Add `Documentation` for NthValueAgg
- [ ] Port / Add `Documentation` for Regr
- [ ] Port / Add `Documentation` for Stddev
- [ ] Port / Add `Documentation` for StddevPop
- [ ] Port / Add `Documentation` for StringAgg
- [ ] Port / Add `Documentation` for Sum

### Describe the solution you'd like

One (or more) PRs that
1. port the documentation for the above named functions from the static docs to code
2. Bonus points:  add sql examples should be added for all functions
3. Remove the documentation from the static docs

Here are some example PRs of doing this:
1. https://github.com/apache/datafusion/pull/12775 from @Omega359 
3. https://github.com/apache/datafusion/pull/12742

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jonathanc-n**
## Which issue does this PR close?

Closes #12827.

## Rationale for this change
Migrate aggregate functions from static docs to new format.

## What changes are included in this PR?
Migrated aggregate functions.

### CODE REVIEW

**Comment by jonathanc-n** [comment]
@alamb @Omega359  I wasn't sure how to deal with the regr functions as their file is a little unique and I am not sure how to deal with them. We could possibly deal with them in another pr.

**Comment by alamb** [comment]
> @alamb @Omega359 I wasn't sure how to deal with the regr functions as their file is a little unique and I am not sure how to deal with them. We could possibly deal with them in another pr.

Yes, let's handle them in a follow on PR

> Also might need to look deeper into some definitions and examples for some that didnt have old documentation yet (StringAgg, Grouping, NthValueAgg)

I'll try and make a PR for these -- it is great we have found a list of functions that were not previously documented

**Review by alamb — APPROVED** [review]
Looks great to me -- thank you @jonathanc-n

**Comment by alamb** [comment]
I made a PR for the `regr` functions in https://github.com/apache/datafusion/pull/12871

**Review by Omega359 — COMMENTED** [review]
Nice work! I left a few suggestions for improvements

**Comment by Omega359** [comment]
Since this was merged already if you want we can create a followup ticket for handling the suggestions.

**Comment by jonathanc-n** [comment]
@Omega359 Yep sounds good, thanks for the review!

**Pull request merged**
