### PR TITLE
Pass BigQuery options to the ArrowSchema

### LINKED ISSUE #10589: Pass per-field BigQuery `OPTIONS` values to the LogicalPlan's Arrow Schema
### Is your feature request related to a problem or challenge?

I've been reading and learning the TableProvider APIs and have finally gotten around to taking a serious look at implementing support for `CREATE EXTERNAL TABLE`. I started down the road of using the statement level `OPTIONS` for adding field specific key/value config pairs similar to how the Parquet provider does with the `OPTION::COLUMN.NESTED.PATH` keys. However, my particular use case has quite a few field specific possible options that would be decently more ergonomic with field level options so I went looking for how I might be able to customize the SQL parser to support something of that nature.

After many false starts I ended up stumbling over the [BigQuery column options support](https://docs.rs/sqlparser/latest/sqlparser/ast/enum.ColumnOption.html#variant.Options) and thought that would be perfect. While I was a bit disappointed its not directly supported, it turned out to be relatively easy to plumb through so that's what I've done.

### Describe the solution you'd like

I'm not tied to anything specific beyond "allow for column specific key/value configuration options". The PR I'll open after filing this issue is one possible implementation, but it doesn't have to be *the* implementation by any means.

### Describe alternatives you've considered

My original thought was to basically that I was going to have to go the route used in the [`sql_dialect.rs`](https://github.com/apache/datafusion/blob/main/datafusion-examples/examples/sql_dialect.rs) where I would basically have to reimplement the `CREATE EXTERNAL TABLE` logic and then somehow plumb my extra options around.

And the reason I went that direction was my first (hacky) though was to re-parse the `CreateExternalTable::definition` field but it apparently doesn't keep the actual original SQL around (at least via the cli AFAICT).

### Additional context

I've got no idea whether the reaction to this will be "Oh, neat!" or "Ewww, gross!". I'm not particularly tied to it because in the end I can always just go to the statement wide options, though given how easy it was to add it seems like it might be acceptable?

### PR DESCRIPTION
**Pull request by davisp**
## Which issue does this PR close?

Closes #10589

## Rationale for this change

Provide per-column key/value options in the `CREATE EXTERN TABLE` statement.

## What changes are included in this PR?

This sets the BigQuery column `OPTIONS` key/values into the Arrow Schema's fields' metadata.

## Are these changes tested?

Barely. I assume I'll need to add a couple more, but I figured I'd wait until I see what sort of enthusiasm this proposal receives.

## Are there any user-facing changes?

Users can now access any parsed BigTable options to each Field's metadata. This allows for TableProvider/TableProviderFactory implementations the ability to accept per-field options. For a query like such:

```sql
CREATE EXTERNAL TABLE test(
  col1 bigint NULL,
  col2 bigint NOT NULL OPTIONS(compression='zstd(5)')
)
STORED AS parquet
LOCATION 'foo.parquet';
```

This results in the field 'col2' on the Arrow Schema having a metdata value of `{"sql_option.compression", "'zstd(5)'"}`.

I think technically this might be able to break downstream users in this scenario:

1. For some reason they are using BigQuery OPTIONS clauses in their `CREATE EXTERN TABLE` column definitions.
2. In their TableProviderFactory, they are attempting to access and use Field metadata in such a way that the now present `sql_option.*` keys breaks things.

The first requirement here seems fairly unlikely to me? I'm making the rough assumption that a "standard" BigQuery table creation statement would fail to parse as a Datafusion `CREATE EXTERN TABLE` statement and thus it'd limit to people who have a) translated a BigQuery statment to a Datafusion statement while keeping their column `OPTIONS` even though they don't actually get passed to the TableProviderFactory.

For the second half, I could see this actually being rather common (that a `MyThing::from(arrow_schema)` blows up with unexpected metadata). Though the intersection of these two sets seems like it'd be tiny?

### CODE REVIEW

**Comment by davisp** [comment]
Also, for anyone more familiar with datafusion and/or sqlparser, one thing I wasn't 100% on was how to represent the metadata value. For now I've just called format on it, but I have the nagging suspicion there might be a way to serialize those so that TableProviderFactor folks can unserialize them more easily rather than having to resort to things like stripping `'` and `"` blindly when converting the DFSchema to whatever they're working with.

**Review by alamb — COMMENTED** [review]
Thank you @davisp  -- this is quite cool

One thing we probably need to do is to add some documentation on 
https://datafusion.apache.org/user-guide/sql/ddl.html#create-external-table

to explain how this works

The one thing I worry about is how the OPTIONs clause on the column behaves differently to the OPTIONs clause on the `CREATE` command

```sql
CREATE EXTERNAL TABLE t(
  c1 int OPTIONS(foo='bar') -- <-- these options go on schema metadata
)
STORED AS CSV 
LOCATION 'foo.csv'
OPTIONS('has_header' true) -- <-- these options have a different format and a different meaning
```

What do you think about a more explicit synteax

```sql
CREATE EXTERNAL TABLE t(
  c1 int METADAA(foo='bar') -- <-- these options go on schema metadata
)
STORED AS CSV 
LOCATION 'foo.csv'
```

This would require some additional plumbing in the datafusion parser, but I think is clearer what is going on


cc @ozankabak  and @metesynnada  who have been thinking about these syntaxes I think

**Comment by ozankabak** [comment]
I agree with @alamb. Maybe we can do a quick survey on how different systems take per-column schema metadata and try to elucidate the best DF syntax from that

**Comment by davisp** [comment]
@alamb That's an excellent point on the possible confusion between the two slightly different syntaxes for the same keyword in a statement. I obviously just went with what already existed but in hindsight that seems like some pretty fertile footgun ground best left untilled.

I'll take a look at updating the parser to go with the `METADATA` keyword instead of `OPTIONS`. Just as a shortcut for my learning, would you expect that change to happen in the datafusion crates or in the sqlparser crate? I'm still not 100% on how that delineation works and given that the column `OPTIONS` isn't part of the dialect trait I'm not immediately certain where that change would be expected to happen.

As to docs and bits, I knew I'd need to add something but figured I'd wait to get things generally agreed upon before spending too much time on the details. A related question I had was wether we'd want to update the Parquet compression option to use this approach at the same time (and anything else that has similar column specificity)? I've not read datafusion's deprecation policy, but adding it in a backwards compatible manner seems straightforward. Column metadata overriding the create options seems unsurprising while not breaking anything.

**Comment by davisp** [comment]
@alamb I've updated things to use `METADTA(foo='bar')` though I'm not 100% on whether I've done it acceptably as I've basically only just allowed the use of `METADATA` in place of `OPTIONS` while not preventing the use of `OPTIONS`. Though given it was previously accepted (and ignored) I'd think that's not a big deal? If we only document `METADATA` the fact that `OPTIONS` works seems not super important. If you think that's a bit loosey goosey we could probably drop that `OPTIONS` version on the floor [here](https://github.com/apache/datafusion/blob/7bd4b53ffa12589340e4d7b4cf70df11f3403865/datafusion/sql/src/parser.rs#L669).

@ozankabak I'm not entirely sure what you're asking to survey. Do you mean looking at various SQL dialects or various datafusion projects that are implementing `TableProvider`? For SQL dialects, I won't claim to have extensive knowledge on the various dialects, but based on my reading of the sqlparser source, this seems specific to the BigQuery dialect. However, there is a [ColumnOption::DialectSpecific](https://docs.rs/sqlparser/0.46.0/sqlparser/ast/enum.ColumnOption.html#variant.DialectSpecific) so that might be something to investigate?

As for the "how do `TableProvider` implementations deal with it, I'd assume most folks are just doing the `OPTIONS("option::column.nested.whatever" "value")` like is done for the Parquet compression option? At the end of the day we're constrained by the Arrow Field::metadata being a `HashMap<String, String>` so I'm not sure how far to go looking  on that front.

**Comment by davisp** [comment]
Speaking of the Arrow metadata constraints, I'm still pondering how best to try and maintain some semblance of type information here. Looking through the dependency tree it seems like it could be reasonable to add a `serde_json` dependency to the `datafusion-sql` crate.

However, I can't convince myself in either direction whether laundering the `sqlparser::ast::Expr` tree through JSON would be worth it or not.

**Comment by metegenez** [comment]
There is a robust method to define column-specific options in Datafusion table options. I believe there should be a single way to do this in Datafusion, but BigQuery is widely used and well-regarded in the community. I find the proposed method easier to read, but ultimately, this should be a decision made by the community as @ozankabak said.

**Comment by ozankabak** [comment]
@davisp what I meant was looking at how other dialects (and systems using those dialects, such as BigQuery) handle column-specific metadata and analyze pros and cons of various approaches.

As @metegenez says, we already support column specific options today, as in:
```sql
COPY source_table
TO 'test_files/scratch/copy/table_with_options/'
STORED AS PARQUET
OPTIONS (
'format.compression::col1' 'zstd(5)',
'format.compression::col2' snappy,
'format.bloom_filter_fpp::col2' 0.456,
'format.encoding::col1' DELTA_BINARY_PACKED,
'format.dictionary_enabled::col2' true,
)
```
So the question really is to decide whether we want to add shortcuts, for user convenience, that set these options and use the existing machinery underneath.

The decision will probably boil down to one of the three choices:
1. We may decide we don't need to/shouldn't support dialect shortcuts at the upstream level. The argument for this is that if we support BigQuery, why not some other system X too? Also, if we have such support for this feature, why not also for another feature?
2. We may decide to support all major dialect shortcuts for this purpose. If we do this, we probably should have the same attitude for other features as well.
3. Hybrid: We may go with 1, but decide that having a shortcut is useful, so design/choose a "DF syntax" for it and only support that.

In 1 and 3, downstream users of DF can add more dialect support according to their needs thanks to DF's extensibility. And if DF creates any friction while doing that, we obviously should address those inconveniences upstream.

**Comment by davisp** [comment]
@metegenez Of course on it being a community decision. It is an ASF project after all. 😄 

I've probably led everyone astray by naming this "BigQuery Options" because that just happened to be what the internal AST node type was labeled as in the sqlparser crate. I'm not at all tied to that syntax or even the general shape of the syntax. It was just the easiest way I found to attach arbitrary metadata directly to each column in a `create external table` statement. Now that its using `METADATA` instead of `OPTIONS`, its not even BigQuery related anymore.

@ozankabak That's an interesting point about anything that wants to support `COPY` might have to support the string based parsing. However, [given this PR](https://github.com/apache/datafusion/pull/9604), it seems like there'd be openness on creating new syntax that mimics any new syntax on the `CREATE EXTERNAL TABLE` statement.

As to your three options, unless I'm mistaken (and I'll point out again, I'm very new here, so I could absolutely be missing something), but my reading of the implementation of `DFParser` vs `sqlparser::Parser` makes it seem to me like Option 3 has already been chosen (implicitly or not). Which means all we need to do is figure out what DataFusion should support and implement it.

As to comparing against other dialects, perhaps I wasn't as clear as I could be. But if we assume that `sqlparser`'s existing dialects are all correctly/completely implemented then we have these options to consider:

1. Don't attach metadata directly to columns (i.e., the current DataFusion approach)
2. BigQuery's `OPTIONS` keyword in the column list
3. Some new syntax we invent to attach metadata to columns

Since I've replaced `OPTIONS` with `METADATA` I guess this PR is technically in the third option, though I'd also consider a completely different syntax if someone cares enough to go and invent it. I'd even be happy to implement it if we just come up with a grammar everyone agrees on. Though for my needs a `col1 BIGINT NOT NULL METADATA(key1=val1, key2=val2, ...)` syntax is more than enough and also feels like the right level of "general enough for others while not significantly increasing parser complexity".

Also, it occurs to me to point out that this syntax wouldn't be mandatory for anything. Patching the parser with this extra syntax doesn't require other `TableProviderFactory` implementations from supporting or using it. Though I'd personally vote in favor of it over the existing approach and would be more than happy to do that implementation as part of this PR. That said, I understand not wanting to rush into new syntax given backwards compatibility concerns. Though I think allowing syntax vs using syntax should be separate concerns as allowing it seems to fall squarely into the "reducing friction for downstream users" category.

**Comment by ozankabak** [comment]
The aim has been to make the `COPY` and `CREATE EXTERNAL TABLE` statements use the same `OPTIONS` syntax. The PR you mention was actually a part of multi-PR effort to make this so and arrive at a unified, consistent syntax. I should have given the example using the `CREATE EXTERNAL TABLE` statement -- using `COPY` misled you. However I'm not sure if we are at 100% on this yet -- e.g. I don't know if we write a `CREATE EXTERNAL TABLE` query today with `OPTIONS (
'format.compression::col1' 'zstd(5)')` whether the metadata will be set correctly. Nevertheless, even if it doesn't, it should/will shortly. 

So, I'm not sure if we are doing

> Don't attach metadata directly to columns (i.e., the current DataFusion approach)

If so, that's certainly not the end state we want to be in.

This is why I referred to the proposed `METADATA` syntax as a shortcut (relative to doing it within `OPTIONS`) in Option 3. We will certainly extend the `OPTIONS` mechanism to cover this case if it doesn't already, but it may also be worthwhile to have a shortcut way (e.g. `METADATA`). I will take a look at how other systems approach this.

**Comment by alamb** [comment]
I skimmed through the commentary on this PR -- and it wasn't immediately clear to me what the current plan is. Are we agreed on a different approach? Are we proposing to proceed with this PR? Something else?

Thanks agian for the help and comments @davisp @ozankabak and @metegenez

**Comment by alamb** [comment]
Marking as a draft as I am trying to work through the review queue

**Pull request closed without merging**
