### PR TITLE
Remove deprecated datafusion_physical_expr::functions module

### PR DESCRIPTION
**Pull request by findepi**
Cleanup.

### CODE REVIEW

**Comment by alamb** [comment]
Nice -- this was likely left over from when we ported functions. Very cool

**Review by alamb — APPROVED** [review]
Great find -- thank you @findepi

**Review by lewiszlw — APPROVED** [review]

**Comment by jayzhan211** [comment]
I thought this was reserved for backward compatible, but I'm ok to remove it.

**Comment by alamb** [comment]
> I thought this was reserved for backward compatible, but I'm ok to remove it.

I think the idea is that the only `pub` functions have been deprecated for around 6 months, which should have been enough time to allow people to migrate to using different APIs

**Comment by alamb** [comment]
Thanks @findepi @jayzhan211 and @lewiszlw

**Pull request merged**
