### PR TITLE
chore: Remove `window_functions_new` docs

### LINKED ISSUE #12740: [EPIC] Automatically generate all function documentation from code
### Is your feature request related to a problem or challenge?

Currently, when we add a new function to DataFusion library we have to remember to document that function in the [documentation](https://datafusion.apache.org/user-guide/sql/scalar_functions.html), but currently we have to remember this during code review. 

This has a few downsides:
1.  we have forgotten to document some functions
2.  the documentation has drifted over time, 
3. help text for various functions can only be found on the DataFusion website, and not, for example within the function itself. 

@Omega359 has created the basic framework for automatically generating content in https://github.com/apache/datafusion/pull/12668

This ticket tracks the work required to port the rest of the documentation to programatic form

### Tasks
- [x] https://github.com/apache/datafusion/issues/12432
- [x] https://github.com/apache/datafusion/pull/12743
- [x] https://github.com/apache/datafusion/pull/12745
- [x] https://github.com/apache/datafusion/issues/13139
- [x] https://github.com/apache/datafusion/issues/12741
- [ ] https://github.com/apache/datafusion/issues/13171
- [ ] Add support for `DESCRIBE xyz`; where xyz is a function. Ideally this would support not just the core functions in DF but also any added externally (for example those in https://github.com/datafusion-contrib/datafusion-functions-extra) and verify it works in the CLI
- [ ] Look into generating the function sections in expressions.md (it's a bit out of date) 
- [x] [Make generate_function_docs.sh error if there is a function without documentation](https://github.com/apache/datafusion/issues/12872)

### Aggregate Function Documentation Migration
- [x] #12827
- [x] Port / Add `Documentation` for BitwiseOperation
- [x] Port / Add `Documentation` for VarianceSample https://github.com/apache/datafusion/pull/12742
- [x] Port / Add `Documentation` for VariancePopulation https://github.com/apache/datafusion/pull/12742

### Scalar Function Documentation Migration
- [ ] https://github.com/apache/datafusion/issues/11172
- [x] https://github.com/apache/datafusion/pull/12775
- [x] https://github.com/apache/datafusion/issues/12927
- [x] #12828
- [x] #12859
- [x] #12858
- [x] #12867
- [x] #12868
- [x] #12934
- [x] #12935

### Window Function Documentation Migration
- [x] Port / Add `Documentation` for `Lead`
- [x] Port / Add `Documentation` for `RowNumber`
- [x] #12936

### PR DESCRIPTION
**Pull request by jonathanc-n**
## Which issue does this PR close?

- Closes #12740 
- Closes https://github.com/apache/datafusion/issues/13171

### CODE REVIEW

**Comment by jonathanc-n** [comment]
For the future, should we be adding sql examples for the window functions?

**Comment by alamb** [comment]
> For the future, should we be adding sql examples for the window functions?

Yes that would be awesome -- any chance you could file a ticket  to track doing so?  In case it helps, here is a PR with an example of how to do: https://github.com/apache/datafusion/pull/13390

**Review by alamb — APPROVED** [review]
Outstanding -- thank you @jonathanc-n 


FYI @Omega359 -- the project is finally done!

**Comment by Omega359** [comment]
WOOT! I'm glad we were able to get this functionality into DF - I think it'll be better for it!

**Comment by alamb** [comment]
> WOOT! I'm glad we were able to get this functionality into DF - I think it'll be better for it!

100% -- it was also really cool to see so many people involved. Talk about a community effort!

**Pull request merged**
