### PR TITLE
refactor: change some `hashbrown` `RawTable` uses to `HashTable`

### PR DESCRIPTION
**Pull request by crepererum**
## Which issue does this PR close?
For #13256, but only parts of it.

## Rationale for this change
Prepare `hashbrown` 0.15 upgrade.

## What changes are included in this PR?
- `HashTableAllocExt`
- a few migrations

## Are these changes tested?
Existing tests pass.

## Are there any user-facing changes?
No.

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
Looks good -- I am running benchmarks and will report back

**Comment by crepererum** [comment]
I would be surprised if there's a notable difference, esp. for this change. Under the hood, it's basically all the same, see

https://docs.rs/hashbrown/0.14.5/src/hashbrown/table.rs.html

**Comment by alamb** [comment]
> I would be surprised if there's a notable difference, esp. for this change. Under the hood, it's basically all the same, see

I agree - I just want to be sure

**Comment by alamb** [comment]
I ran the benchmarks again and see no change. Thus I conclude this PR does not change performance significantly

```
--------------------
Benchmark clickbench_partitioned.json
--------------------
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┓
┃ Query        ┃  main_base ┃ crepererum_issue13256_a ┃       Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━┩
│ QQuery 0     │     2.40ms │                  2.35ms │    no change │
│ QQuery 1     │    40.13ms │                 40.60ms │    no change │
│ QQuery 2     │    98.55ms │                 96.76ms │    no change │
│ QQuery 3     │   108.03ms │                110.34ms │    no change │
│ QQuery 4     │   946.21ms │                911.31ms │    no change │
│ QQuery 5     │   988.30ms │                956.43ms │    no change │
│ QQuery 6     │    39.03ms │                 37.15ms │    no change │
│ QQuery 7     │    42.98ms │                 43.53ms │    no change │
│ QQuery 8     │  1022.74ms │                993.36ms │    no change │
│ QQuery 9     │  1350.46ms │               1325.77ms │    no change │
│ QQuery 10    │   289.45ms │                287.22ms │    no change │
│ QQuery 11    │   324.72ms │                314.36ms │    no change │
│ QQuery 12    │  1005.26ms │                976.73ms │    no change │
│ QQuery 13    │  1467.81ms │               1440.12ms │    no change │
│ QQuery 14    │   925.44ms │                880.82ms │    no change │
│ QQuery 15    │  1095.23ms │               1078.33ms │    no change │
│ QQuery 16    │  2049.77ms │               1997.86ms │    no change │
│ QQuery 17    │  1875.25ms │               1845.67ms │    no change │
│ QQuery 18    │  4307.22ms │               4249.00ms │    no change │
│ QQuery 19    │    96.50ms │                 95.52ms │    no change │
│ QQuery 20    │  1245.65ms │               1248.43ms │    no change │
│ QQuery 21    │  1529.59ms │               1456.04ms │    no change │
│ QQuery 22    │  2693.39ms │               2597.35ms │    no change │
│ QQuery 23    │  8735.35ms │               8469.37ms │    no change │
│ QQuery 24    │   530.10ms │                510.30ms │    no change │
│ QQuery 25    │   436.66ms │                418.76ms │    no change │
│ QQuery 26    │   590.06ms │                573.77ms │    no change │
│ QQuery 27    │  1904.35ms │               1848.69ms │    no change │
│ QQuery 28    │ 13237.28ms │              13498.55ms │    no change │
│ QQuery 29    │   533.29ms │                531.26ms │    no change │
│ QQuery 30    │   916.57ms │                887.13ms │    no change │
│ QQuery 31    │   962.64ms │                934.63ms │    no change │
│ QQuery 32    │  4134.49ms │               4093.42ms │    no change │
│ QQuery 33    │  4093.70ms │               4044.19ms │    no change │
│ QQuery 34    │  4152.12ms │               4067.67ms │    no change │
│ QQuery 35    │  1357.88ms │               1346.74ms │    no change │
│ QQuery 36    │   240.73ms │                228.88ms │    no change │
│ QQuery 37    │    96.36ms │                 97.53ms │    no change │
│ QQuery 38    │   136.34ms │                134.69ms │    no change │
│ QQuery 39    │   442.49ms │                439.20ms │    no change │
│ QQuery 40    │    55.78ms │                 60.72ms │ 1.09x slower │
│ QQuery 41    │    46.95ms │                 46.35ms │    no change │
│ QQuery 42    │    63.32ms │                 63.70ms │    no change │
```

**Review by alamb — APPROVED** [review]
Thank you @crepererum

**Comment by jayzhan211** [comment]
Thanks @crepererum @alamb

**Pull request merged**
