### PR TITLE
chore: Move `OptimizeAggregateOrder` from core to optimizer crate

### PR DESCRIPTION
**Pull request by jonathanc-n**
## Which issue does this PR close?

Part of #11502

### CODE REVIEW

**Comment by jonathanc-n** [comment]
@jayzhan211 @lewiszlw Are there preferences/limits for how much the dependencies should be moved between the crates?

**Comment by jayzhan211** [comment]
> @jayzhan211 @lewiszlw Are there preferences/limits for how much the dependencies should be moved between the crates?

What do you mean by "how much the dependencies"？

**Comment by jonathanc-n** [comment]
Sorry, grammar mistake, does it matter how many dependencies are added to the optimizer crate during this transition?

**Comment by jayzhan211** [comment]
> Sorry, grammar mistake, does it matter how many dependencies are added to the optimizer crate during this transition?

The number of dependencies isn’t the issue; what matters is whether it makes sense to add them

**Review by jayzhan211 — APPROVED** [review]
👍

**Pull request merged**
