### PR TITLE
chore: temporarily disable Windows Rust flow

### PR DESCRIPTION
**Pull request by comphead**
## Which issue does this PR close?

Related to #13726 .

## Rationale for this change

Presumably there is an issue in Github runners starting from last year and causing the Window Rust flow to run for 1.5h without any particular reason. Commenting out the flow for now and waiting for a new GH Windows runner

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thanks @comphead 

FYI @Omega359

**Comment by comphead** [comment]
Thanks for the review

**Comment by Omega359** [comment]
While we're at it the intel mac tests are not all that useful.

**Comment by alamb** [comment]
> While we're at it the intel mac tests are not all that useful.

I agree though maybe it is useful. I wrote up a larger story about testing improvements here:
- https://github.com/apache/datafusion/issues/13845

**Pull request merged**
