### PR TITLE
Fix Regex signature types

### LINKED ISSUE #12664: `REGEX_LIKE` and `REGEX_MATCH` don't support `LargeUtf8` type
### Describe the bug

While working on #12415, I found `REGEX_LIKE` and `REGEX_MATCH` don't support `LargeUtf8` type.

### To Reproduce

It can be reproduced by the following SQL
```
> select regexp_like(arrow_cast('abcdef', 'LargeUtf8'), 'bc');
Internal error: could not cast value to arrow_array::array::byte_array::GenericByteArray<arrow_array::types::GenericStringType<i64>>.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker

> select regexp_match(arrow_cast('abcdef', 'LargeUtf8'), 'bc');
Internal error: could not cast value to arrow_array::array::byte_array::GenericByteArray<arrow_array::types::GenericStringType<i64>>.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

### Expected behavior

They should work well like `Utf8`
```
> select regexp_like(arrow_cast('abcdef', 'Utf8'), 'bc');
+-----------------------------------------------------------------+
| regexp_like(arrow_cast(Utf8("abcdef"),Utf8("Utf8")),Utf8("bc")) |
+-----------------------------------------------------------------+
| true                                                            |
+-----------------------------------------------------------------+
1 row(s) fetched. 
Elapsed 0.010 seconds.

> select regexp_match(arrow_cast('abcdef', 'Utf8'), 'bc');
+------------------------------------------------------------------+
| regexp_match(arrow_cast(Utf8("abcdef"),Utf8("Utf8")),Utf8("bc")) |
+------------------------------------------------------------------+
| [bc]                                                             |
+------------------------------------------------------------------+
1 row(s) fetched. 
Elapsed 0.016 seconds.
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by blaginin**
## Which issue does this PR close?

Closes #12664.

## Rationale for this change

As pointed out in the original issue, `REGEX_MATCH` and `REGEX_LIKE` fail if the first argument is `LargeUtf8` but the second (or third) argument is `Utf8`. We were performing `as_generic_string_array::<i64>` on `&GenericStringArray<i32>`, which caused the issue.

## What changes are included in this PR?

Regex Match implementation in Apache Arrow requires the input and patterns [to have the same type](https://github.com/apache/arrow-rs/blob/3293a8c2f9062fca93bee2210d540a1d25155bf5/arrow-string/src/regexp.rs#L409), and the flags [to have the same type as well](https://github.com/apache/arrow-rs/blob/3293a8c2f9062fca93bee2210d540a1d25155bf5/arrow-string/src/regexp.rs#L430). I have reflected this change in the function signatures. 

## Are these changes tested?

Yes, by `string_query.slt.part`

## Are there any user-facing changes?

No, only a bugfix.

### CODE REVIEW

**Comment by goldmedal** [comment]
Thanks @blaginin, for working on this! There are some TODO items related to this issue. Could you help address them?
- enable the share test case.
https://github.com/apache/datafusion/blob/02427674eef658b9b0acb7142f18e8c1520bdb17/datafusion/sqllogictest/test_files/string/string_query.slt.part#L859-L860
- Clean up the type-specific test case.
https://github.com/apache/datafusion/blob/02427674eef658b9b0acb7142f18e8c1520bdb17/datafusion/sqllogictest/test_files/string/string.slt#L66
https://github.com/apache/datafusion/blob/02427674eef658b9b0acb7142f18e8c1520bdb17/datafusion/sqllogictest/test_files/string/string_view.slt#L68
https://github.com/apache/datafusion/blob/02427674eef658b9b0acb7142f18e8c1520bdb17/datafusion/sqllogictest/test_files/string/dictionary_utf8.slt#L56

You can test them using the following command
```
cargo test --test sqllogictests -- string/
```

**Comment by alamb** [comment]
Thank you @blaginin  and @goldmedal  for the review. Sounds like this PR is quite close ❤️

**Comment by blaginin** [comment]
Thanks for the review, @goldmedal! I've [uncommented](https://github.com/apache/datafusion/pull/12690/commits/849b9854205cb8265d0a003d9668e64ec9af2d3a) your tests and also [added](https://github.com/apache/datafusion/pull/12690/commits/dbdb2fbb0dd0bb74e0f3ee3cab00a7585747421b) flags testing. Quite a cool string test setup, by the way! ;)

**Review by alamb — APPROVED** [review]
Looks great to me -- thank you @blaginin  and @goldmedal  🏆

**Review by goldmedal — APPROVED** [review]
Thanks @blaginin for working on this and enhancing the tests. 👍
It looks good to me.

**Comment by alamb** [comment]
🚀

**Pull request merged**
