### PR TITLE
Minor: Switch LastValue SQL workflow to UDAF version

### PR DESCRIPTION
**Pull request by jayzhan211**
## Which issue does this PR close?

Closes #.

Part of https://github.com/apache/arrow-datafusion/issues/8708

## Rationale for this change

After this change, LAST_VALUE goes to the registered UDAF instead of builtin one.

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thanks @jayzhan211  -- this looks very cool. I think we should remove the built in window function with the same PR so it is clear which versions are being used. 

If we leave both in it will be quite confusing

**Comment by jayzhan211** [comment]
Then I think we need to support ordering for the window function before this

**Comment by jayzhan211** [comment]
To support replacing window first/last, there are many issues to be solved. 

Including replacing first/last in convert_firsts_last rule, and support sliding accumulator for udaf, and support list instead of NUMERIC signature.

**Comment by alamb** [comment]
> To support replacing window first/last, there are many issues to be solved.

I wonder if starting with simpler aggregates (like `approx_distinct`) might be a good idea. They are probably simpler to port and would let us work through some of the details before breaking off the larger more complex ones

`first_value` / `last_value` are likely the most complex as they are order aware and can be used as aggregates and window functions

**Comment by jayzhan211** [comment]
> > To support replacing window first/last, there are many issues to be solved.
> 
> I wonder if starting with simpler aggregates (like `approx_distinct`) might be a good idea. They are probably simpler to port and would let us work through some of the details before breaking off the larger more complex ones
> 
> `first_value` / `last_value` are likely the most complex as they are order aware and can be used as aggregates and window functions

While I try to deprecate first/last, I found that window function can works with UDAF without additional change.

> Including replacing first/last in convert_firsts_last rule, and support sliding accumulator for udaf, and support list instead of NUMERIC signature.

The issue I mentioned is part of a need for deprecating first/last, not for window function.

**Pull request closed without merging**
