### PR TITLE
Fix unparsing offset

### LINKED ISSUE #12538: Fix unparsing OFFSET
### Describe the bug

Unparsing OFFSET does not work as expected.

### To Reproduce

Parse and unparse the query `SELECT 1 OFFSET 95`.

### Expected behavior

The query should be unparsed completely, including OFFSET.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Stazer**
## Which issue does this PR close?

Closes #12538.

## What changes are included in this PR?

I have added a missing block for unparsing OFFSET.

## Are these changes tested?

Yes. Unit-Tests are provided.

## Are there any user-facing changes?

No.

### CODE REVIEW

**Review by phillipleblanc — APPROVED** [review]
Looks great, thanks!

**Review by alamb — APPROVED** [review]
Thank you @Stazer  and @phillipleblanc  for the reivew

**Comment by alamb** [comment]
Looks like there are some small CI failures on this PR

**Comment by alamb** [comment]
🚀  -- thanks again

**Pull request merged**
