### PR TITLE
Removed Arc wrapping for AggregateFunctionExpr

### LINKED ISSUE #12257: Don't wrap `Arc` for `AggregateFunctionExpr`
If `AggregateFunctionExpr` is not cloned massively, we could remove `Arc`, similar to that we doesn't wrap `Arc` for `Expr`.

_Originally posted by @jayzhan211 in https://github.com/apache/datafusion/pull/12096#discussion_r1726365405_

### PR DESCRIPTION
**Pull request by athultr1997**
## Which issue does this PR close?

Closes #12257.

## Rationale for this change

The trait `AggregateFunctionExpr` was removed previously in #12096 . This is a follow-up PR that removes the usage of Arc wrapping for`AggregateFunctionExpr`.

### CODE REVIEW

**Comment by alamb** [comment]
Thanks @athultr1997  -- this looks really neat

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @athultr1997 

cc @lewiszlw 

I am also going to mark this PR as an API change as I think several of the functions are pub

**Review by jayzhan211 — APPROVED** [review]
👍

**Review by lewiszlw — APPROVED** [review]
LGTM. Thank you @athultr1997.

**Comment by alamb** [comment]
🚀

**Comment by alamb** [comment]
Thanks again @athultr1997  and @jayzhan211  and @lewiszlw  for the reviews

**Pull request merged**
