### PR TITLE
Implement mode function

### LINKED ISSUE #12248: Support `mode` in Aggregation function
### Is your feature request related to a problem or challenge?

The most frequent value.

### Describe the solution you'd like

```sql
D SELECT mode(col) FROM VALUES ([1, 2]), ([1, 2]), ([2, 3]) AS tab(col);
┌───────────┐
│ mode(col) │
│  varchar  │
├───────────┤
│ [1, 2]    │
└───────────┘

-- The function returns either 1 or 2, but not 3
> SELECT mode(col) FROM VALUES (1), (1), (2), (2), (3) AS tab(col);
 1

> SELECT mode(col) FROM VALUES (NULL), (NULL) AS tab(col);
 NULL
```

### Describe alternatives you've considered

_No response_

### Additional context

https://duckdb.org/docs/sql/functions/aggregates#modex
https://docs.databricks.com/en/sql/language-manual/functions/mode.html

### PR DESCRIPTION
**Pull request by dmitrybugakov**
## Which issue does this PR close?

Closes #12248

### CODE REVIEW

**Comment by alamb** [comment]
RElated comment: https://github.com/apache/datafusion/issues/12254#issuecomment-2353615046

**Comment by dmitrybugakov** [comment]
Hi @alamb,

Could you help me choose the right approach?

I’ve started working on [this issue](https://github.com/apache/datafusion/issues/12254#issuecomment-2356571864). We chose "mode" as the first function for datafusion-functions-extra, but I’ve run into a challenge. My implementation involves patching ArrowBytesMap with new methods.

Should I first patch ArrowBytesMap and then wait for the new release of the DataFusion core, or is there a more efficient way to proceed?

**Comment by alamb** [comment]
> Should I first patch ArrowBytesMap and then wait for the new release of the DataFusion core, or is there a more efficient way to proceed?

I would recommend:
1. Make a PR to update the new method
2. In the code of `datafusion-functions-extra` make a copy of ArrowBytesMap with the new methods you need with a link back to the PR that adds the APIs

That way you'll be unblocked but still have a path to avoid a second copy of the bytes map

**Comment by dmitrybugakov** [comment]
@alamb thank you!

**Pull request closed without merging**
