### PR TITLE
CI: Fix complaints from newer Clippy versions

### PR DESCRIPTION
**Pull request by comphead**
## Which issue does this PR close?

Closes #.

### CODE REVIEW

**Review by parthchandra — APPROVED** [review]
LGTM

**Review by andygrove — APPROVED** [review]
Thanks @comphead

**Comment by alamb** [comment]
Thank you!

**Comment by viirya** [comment]
Isn't this already fixed by #10723? 😄

**Comment by alamb** [comment]
Double fix 🤔  well it should be *really* fixed now 😆

**Pull request merged**
