### PR TITLE
Fix `plan_to_sql`: Add wildcard projection to SELECT statement if no projection was set

### LINKED ISSUE #11743: `TableScan` plan without projection is not converted correctly to a sql statement
### Describe the bug

when converting a plan that contains a table scan without a projection like this 
```
TableScan: table
```
to a sql using `plan_to_sql`, it gives a wrong select statement 
```sql
SELECT FROM table
```
where the `*` is missing. 

### To Reproduce

you can reproduce it by simply running 

```rust 
 let schema = Schema::new(vec![
            Field::new("id", DataType::Utf8, false),
            Field::new("value", DataType::Utf8, false),
 ]);

 let plan = table_scan(Some('table'), &schema, None)
                 .unwrap()
                 .build()
                 .unwrap();
 let sql = plan_to_sql(&plan).unwrap();
// sql will be set to `SELECT FROM table`
```

### Expected behavior
when a plan doesn't have a projection node, the SQL query should look like 
`SELECT * FROM table` 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LatrecheYasser**
## Which issue does this PR close?

Closes #11743.

## Rationale for this change

This PR will check the `select_builder` in the `select_to_sql_expr` after calling the `select_to_sql_recursively` and if no projection is set, it will add a projection with one element set to `ast::SelectItem::Wildcard(ast::WildcardAdditionalOptions::default())`

## What changes are included in this PR?

The changes described above, and some test cases. 

## Are these changes tested?

Yes. 

## Are there any user-facing changes?

I would say no.

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
Thank you @LatrecheYasser  -- this looks good to me. I started the CI checks and assuming they pass I think this PR is ready to go

**Comment by alamb** [comment]
https://github.com/apache/datafusion/actions/runs/10179108058/job/28167144185?pr=11744 is failing -- I think we can fix that by running `cargo fmt` and committing the result

**Comment by LatrecheYasser** [comment]
> https://github.com/apache/datafusion/actions/runs/10179108058/job/28167144185?pr=11744 is failing -- I think we can fix that by running `cargo fmt` and committing the result

thanks @alamb I will run the `cargo fmt` and push a new commit. Thanks for the quick review

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @LatrecheYasser

**Comment by alamb** [comment]
🚀

**Pull request merged**
