### PR TITLE
[logical-types branch] Backport native and logical types

### PR DESCRIPTION
**Pull request by notfilippo**
While #12853 is still in review I was wandering if I could make some additional progress on the logical-types branch.

### CODE REVIEW

**Comment by jayzhan211** [comment]
clippy error

**Comment by notfilippo** [comment]
It seems unrelated

**Comment by notfilippo** [comment]
I'll open another PR to rebase the branch to main.

**Comment by notfilippo** [comment]
For now I've just cherry-picked the fix commit. Hope that's enough

**Review by alamb — APPROVED** [review]
Since this targets a feature branch it looks good to me -- let's keep it moving

**Pull request merged**
