### PR TITLE
Move Regr_* functions to use UDAF

### LINKED ISSUE #10883: Convert `Regr` to UDAF
### Is your feature request related to a problem or challenge?

Similar to other issues in #8708  Move `Regr` in `datafusion/physical-expr/src/aggregate/regr.rs` to `datafusion/functions-aggregate/src/regr.rs`

### Describe the solution you'd like

_No response_

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by eejbyfeldt**
## Which issue does this PR close?

Closes #10883 and is part of #8708

## Rationale for this change

The motivation is in #8708

## What changes are included in this PR?
This moves Regr to be implemented using UDAF as decided in #8708. To avoid duplicating to much code I had to modify an existing macros and add new one to avoid creating a lot of boilerplate for each one. Let me know if there is some better way of doing it.

## Are these changes tested?
Existing tests cases.

## Are there any user-facing changes?
I think so since we moved the implementations to a different package.

### CODE REVIEW

**Comment by alamb** [comment]
I took the liberty of running cargo fmt and regenerated the vendored data

**Comment by alamb** [comment]
The macos failure https://github.com/apache/datafusion/actions/runs/9502875641/job/26191967199?pr=10898 appears to be related to https://github.com/apache/datafusion/pull/10904 (a flaky fuzz test)

**Comment by alamb** [comment]
Merged up to get the fix for #10904

**Comment by alamb** [comment]
🎉

**Comment by jayzhan211** [comment]
Thanks @eejbyfeldt and @alamb

**Pull request merged**
