### PR TITLE
Initial support for `StringView`, merge changes from `string-view` development branch

### PR DESCRIPTION
**Pull request by alamb**
## Which issue does this PR close?

Part of https://github.com/apache/datafusion/issues/10918

## Rationale for this change

While we were initially developing StringView in DataFusion the required features in parquet/arrow were not yet available and so we made a feature branch pinned to the version of arrow required: https://github.com/apache/datafusion/commits/string-view/

The required functionality for StringView has been releaed in arrow/parquet `51.1.0` and DataFusion now uses that version as of https://github.com/apache/datafusion/pull/11302 

Thus there is no reason for a feature branch so let's bring the changes to main

## What changes are included in this PR?

Merge in all the changes from @Weijun-H @PsiACE  and @XiangpengHao on the `string-view` branch. Specifically: 
* https://github.com/apache/datafusion/pull/10925
* https://github.com/apache/datafusion/pull/10985
* https://github.com/apache/datafusion/pull/10997
* https://github.com/apache/datafusion/pull/11004
* https://github.com/apache/datafusion/pull/11034
* https://github.com/apache/datafusion/pull/11043

## Are these changes tested?

Yes, there are unit tests

## Are there any user-facing changes?
Not yet, but there will be

### CODE REVIEW

**Review by Weijun-H — APPROVED** [review]
LGTM!

**Review by PsiACE — APPROVED** [review]

**Comment by alamb** [comment]
@thinkharderdev or @avantgardnerio  -- would either of you have a few moments to review this PR? We want to merge the work we have so far for StringView into main (that depends on arrow `51.1.0`) and then move on to the additional work that will require 52.2 (e.g.  https://github.com/apache/datafusion/pull/11421)

**Review by thinkharderdev — APPROVED** [review]
lgtm

**Comment by alamb** [comment]
Thank you @thinkharderdev 

cc @XiangpengHao I will now make a string-view2 branch for your next sequence of PRs

**Pull request merged**
