### PR TITLE
Require `Debug` for `PhysicalOptimizerRule`

### PR DESCRIPTION
**Pull request by AnthonyZhOon**
## Which issue does this PR close?
Part of #12555 

## Rationale for this change
Supporting [SessionStateBuilder](https://docs.rs/datafusion/latest/datafusion/execution/session_state/struct.SessionStateBuilder.html) to implement Debug

## What changes are included in this PR?
1. Require `Debug` for PhysicalOptimizerRule
2. `#derive` Debug where necessary
~~3. Add a `&` to take a `&JoinType` in `EnforceDistribution` (not sure why this wasn't a `cargo check` error but rust-analyzer showed it and types seem to require it)~~

## Are these changes tested?

By CI and the compiler

## Are there any user-facing changes?

API change for `PhysicalOptimizerRule` which now requires Debug

### CODE REVIEW

**Comment by AnthonyZhOon** [comment]
Need to add the `api-change` label

**Comment by alamb** [comment]
Looks like there are some small CI failures to address @AnthonyZhOon

**Comment by AnthonyZhOon** [comment]
Okay, clippy lint should be fixed with the revert @alamb , odd that rust-analyzer misled me on the types at the time maybe it was an incomplete compile

**Comment by alamb** [comment]
I think this one is minor enough and non controversial I will merge it in, even though it is an API change

**Pull request merged**
