### PR TITLE
Use // for unparsing DuckDB division operator

### PR DESCRIPTION
**Pull request by Sevenannn**
## Which issue does this PR close?

N/A

## Rationale for this change

In Datafusion, the `/` operator is semantically integer division. When both a & b are integer, `a/b` result is a integer rounded down to 0. When unparsing Datafusion logical plan to DuckDB SQL query, the query needs to follow the same semantic meaning of integer division. Therefore, the `Operator::Divide` needs to be unparsed to `BinaryOperator::DuckIntegerDivide`, which is `//` in DuckDB.

Reference to DuckDB division operator: https://duckdb.org/docs/sql/functions/numeric.html#division-and-modulo-operators. The `//` operator has the same semantic meaning to Datafusion `/` operator
image

## What changes are included in this PR?

- Add `division_operator` method in Dialect trait to return the division operator for a specific Dialect
- Use `BinaryOperator::DuckIntegerDivide` as the division operator for DuckDB Dialect
- Use the `division_operator` of dialect to unparse `Operator::Divide` in Unparser `op_to_sql` method

## Are these changes tested?

Yes

## Are there any user-facing changes?

All division will be unparsed to `//` instead of `/` for DuckDB Dialect.

### CODE REVIEW

**Comment by alamb** [comment]
CI appears to be failing. Marking as a draft

**Review by alamb — APPROVED** [review]
makes sense to me -- thank you @Sevenannn

**Comment by alamb** [comment]
Thanks again @Sevenannn

**Comment by Sevenannn** [comment]
Thanks for reviewing @alamb

**Pull request merged**
