### PR TITLE
docs(variance): Correct typos in comments

### PR DESCRIPTION
**Pull request by pingsutw**
## Which issue does this PR close?

Closes #.

## Rationale for this change
Typo

## What changes are included in this PR?
Correct typos in comments

## Are these changes tested?
Unit tests

## Are there any user-facing changes?
NO

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thank you @pingsutw

**Comment by alamb** [comment]
This PR appears to have a conflict that needs to be addressed prior to merge (perhaps https://github.com/apache/datafusion/pull/10836)

**Comment by pingsutw** [comment]
Resolved the conflict. Thanks for the review

**Comment by alamb** [comment]
Thanks again @pingsutw

**Pull request merged**
