### PR TITLE
Minor: Improve ObjectStoreUrl docs + examples

### PR DESCRIPTION
**Pull request by alamb**
## Which issue does this PR close?

related to https://github.com/apache/datafusion/issues/10616

## Rationale for this change
While working on https://github.com/apache/datafusion/pull/10549 I kept getting confused about what an `ObjectStoreUrl` was / is.

Thus I felt some documentation / examples would help

## What changes are included in this PR?
Add more docs + examples

## Are these changes tested?
new doc examples

## Are there any user-facing changes?
Docs + examples

No functional changes

### CODE REVIEW

**Review by goldmedal — APPROVED** [review]
Thanks @alamb LGTM.
This example clearly explains how to use ObjectStoreUrl.

**Comment by goldmedal** [comment]
On a related note, I found that the usage flow of ObjectStore in DataFusion involves registering the source as a table and then querying the table. This approach makes sense. However, I think it might be possible to provide something like a table function or other methods to allow users to dynamically decide which path they want to scan.

There are similar features in DuckDB and Spark:
- DuckDB: `SELECT * FROM read_parquet('file-path/test.parquet')`
- Spark: `spark.read.parquet('xxxx')`

Does DataFusion already have this feature, or did I miss it? If not, I think it would be a valuable feature for users of object storage.

**Comment by alamb** [comment]
> Does DataFusion already have this feature, or did I miss it? If not, I think it would be a valuable feature for users of object storage.

THis feature is in `datafusion-cli` (not DataFusion core) via a synamic schema provider

```shell
andrewlamb@Andrews-MacBook-Pro-2:~/Software/influxdb_iox$ datafusion-cli
DataFusion CLI v38.0.0
> select * from '/tmp/foo.parquet';
+---------+
| column1 |
+---------+
| 1       |
+---------+
1 row(s) fetched.
Elapsed 0.015 seconds.
```

Automatically allowing access to reading arbtrary files / urls is likely not appropriate for datafusion by default, however having it be an easier feature to add would be good. 

Maybe this would be a good feature to add as an example or maybe even move the dynamic table provider into datafusion core (not enabled by default) if this is a feature others want

**Comment by goldmedal** [comment]
> Maybe this would be a good feature to add as an example or maybe even move the dynamic table provider into datafusion core (not enabled by default) if this is a feature others want
Cool! Thanks for the information!
I think some users may want to use it directly through the core. It's very convenient to build a system that can query object storage dynamically.

**Review by comphead — APPROVED** [review]
lgtm thanks @alamb

**Pull request merged**
