### PR TITLE
Minor: cleanup `.gitignore`

### PR DESCRIPTION
**Pull request by alamb**
## Which issue does this PR close?

Closes #.

## Rationale for this change

While working on https://github.com/apache/datafusion/pull/12034 I noticed a bunch of stuff in .gitignore that was left over from when this code was pulled from the arrow monorepo: https://github.com/apache/arrow/blob/main/.gitignore

## What changes are included in this PR?

Remove the obviously irrelevant parts of .gitignore

I am sure there is more we could remove but this is an improvement already in my mind

## Are these changes tested?
Sort of by CI

## Are there any user-facing changes?
No, this is entirely development process changes

### CODE REVIEW

**Review by PsiACE — APPROVED** [review]
:100:

**Review by comphead — APPROVED** [review]
lgtm thanks @alamb I think those files been added by members compiing the project under different OSs and IDEs. But I agree the local copy of .gitignore should reflect their needs

**Comment by alamb** [comment]
If someone needs additional lines in .gitignore to help their workflow I think we should definitely merge them in -- there is no harm in having more stuff in here.

**Comment by alamb** [comment]
Thanks @comphead

**Pull request merged**
