### PR TITLE
Cleanup GetIndexedField

### PR DESCRIPTION
**Pull request by lewiszlw**
## Which issue does this PR close?

Closes #.

## Rationale for this change

I noticed that `GetIndexedField` is not used anymore after https://github.com/apache/datafusion/pull/10568, so just removed it.

### CODE REVIEW

**Review by jayzhan211 — APPROVED** [review]
👍

**Comment by alamb** [comment]
Thank you @lewiszlw . I merged up from main to resolve a conflict.

**Comment by alamb** [comment]
🚀

**Comment by alamb** [comment]
Thanks @lewiszlw  and @jayzhan211

**Pull request merged**
