### PR TITLE
UpdateD pool.rs

### LINKED ISSUE #6934: Debug dump of MemoryManager
### Is your feature request related to a problem or challenge?

@JayjeetAtGithub and I are investigating improving memory performance for certain queries

When we hit the memory limit, we see different error messages. For example sometimes we see

```
External error: External error: Execution error for 'deduplicate batches'\ncaused by\nResources exhausted: Memory Exhausted while Sorting (DiskManager is disabled)", source: None })
```

And sometimes we see
```
External error: Resources exhausted: Failed to allocate additional 212912 bytes for GroupedHashAggregateStream[2] with 0 bytes already allocated - maximum available is 18446744073705376568"
```

We would like to know what operators are consuming the memory

I theorize the fact that we see different operators appear in the logs is due to the fact when we near the memory limit, any of the operators might be the "canary" that happened to be the operator that asked for memory next, rather than the one that was actually using it all)

### Describe the solution you'd like

I would like some way to know how much each operator is consuming in a particular pool, and prior to returning an allocation error, entering a debug log with this information

The memory pool code is here: https://github.com/apache/arrow-datafusion/blob/main/datafusion/execution/src/memory_pool/pool.rs

I was imagining implementing `Display` for the pools like

```rust
impl Display for GreedyPool  {
 ...
}
```

Which would produce a report like this with the reservations sorted in descending order:
```
GreedyPool 25 allocations, 25630532 used, 332 free, 43942344 capacity
  321433: GroupedHashAggregateStream[0]
  1233: GroupedHashAggregateStream[2]
  24: Deduplicate
```

Then prior to returning a resources exhausted error:
https://github.com/apache/arrow-datafusion/blob/50135e8c039b82d32b57db12ca06d789e9cbea4c/datafusion/execution/src/memory_pool/pool.rs#L87

We would add a log message like

```rust
debug!("Pool Exhausted while trying to allocate {additional} bytes for {reservation} :\n{self}", self)
```

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by TouchstoneTheDev**
# Which issue does this PR close?

Closes #6934

# Rationale for this change

The rationale for this change is to add a debug dump of the MemoryManager to help diagnose memory exhaustion issues in certain queries. The PR proposes implementing the Display trait for the memory pools to produce a report of the reservations sorted in descending order, and adding a log message prior to returning a resources exhausted error.

# What changes are included in this PR?

Implementing the Display trait for the memory pools to produce a report of the reservations sorted in descending order.

# Are these changes tested?

Yes, the changes are tested. The PR includes updates to the MemoryManager tests to include the new functionality.

# Are there any user-facing changes?

No, there are no user-facing changes. The changes are internal to the MemoryManager and are intended to help diagnose memory exhaustion issues in certain queries.

### CODE REVIEW

**Comment by Weijun-H** [comment]
Hi @tanmay-veer , this pr only includes the test, do you push the latest version?

**Comment by tanmay-veer** [comment]
Yes i have only included tests

**Comment by alamb** [comment]
I guess I was hoping to see code that would generate a report like this

```
GreedyPool 25 allocations, 25630532 used, 332 free, 43942344 capacity
  321433: GroupedHashAggregateStream[0]
  1233: GroupedHashAggregateStream[2]
  24: Deduplicate
```

In the debug log 

```
debug!("Pool Exhausted while trying to allocate {additional} bytes for {reservation} :\n{self}", self)
```

**Comment by alamb** [comment]
I think this is not waiting on review currently -- it is waiting for feedback to be addressed, so marking as "Draft"

**Pull request closed without merging**
