### PR TITLE
Backport "physical-plan: Cast nested group values back to dictionary if necessary" (#12586)

### PR DESCRIPTION
**Pull request by matthewmturner**
## Which issue does this PR close?

Part of #12813 applies fix from https://github.com/apache/datafusion/pull/12586

### CODE REVIEW

**Comment by matthewmturner** [comment]
@alamb @Xuanwo FYI

**Review by Xuanwo — APPROVED** [review]
Nice, no conflict. Let's wait CI to be green.

**Comment by alamb** [comment]
close/reopen to trigger CI

**Comment by matthewmturner** [comment]
@alamb FYI i think this is good to go

**Review by alamb — APPROVED** [review]
Thank you @matthewmturner  

cc @brancz

**Pull request merged**
