### PR TITLE
feat: Add MaxTime type for a Time that returns the max on aggregation

### LINKED ISSUE #11754: Add MetricValue that returns the max during aggregation
### Is your feature request related to a problem or challenge?

We have a scenario where we are performing multiple operations in parallel and are only interested in the one that takes the longest. Currently, `MetricValue::Time` is always summed on aggregation.

### Describe the solution you'd like

A new type, `MetricValue::MaxTime`, is implemented that functions the same as `MetricValue::Time` except on aggregation, it returns the max of the two times rather than the sum.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffreyssmith2nd**
## Which issue does this PR close?

Closes #11754

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
It seems somewhat awkward to add a "type" of metric that is logically the same bug just differs in aggregation behavior


I wonder if the same result could be achieved by writing a custom aggregation function

**Comment by jeffreyssmith2nd** [comment]
> It seems somewhat awkward to add a "type" of metric that is logically the same bug just differs in aggregation behavior

I don't necessarily disagree with this, but where would the custom aggregation function live/how would it be used? There are multiple places that `MetricValue::aggregate` is called.

 https://github.com/apache/datafusion/blob/02a9812745406b9cc00c04f9d870b23c4b3c4947/datafusion/physical-plan/src/metrics/mod.rs#L246

https://github.com/apache/datafusion/blob/02a9812745406b9cc00c04f9d870b23c4b3c4947/datafusion/physical-plan/src/metrics/mod.rs#L283

https://github.com/apache/datafusion/blob/02a9812745406b9cc00c04f9d870b23c4b3c4947/datafusion/physical-plan/src/metrics/mod.rs#L289

**Comment by alamb** [comment]
I had some more thoughts on this PR here: https://github.com/apache/datafusion/issues/11754

**Comment by alamb** [comment]
Marking as a draft to signify this isn't waiting on another review.

It isn't clear to me how to proceed with this PR given https://github.com/apache/datafusion/issues/11754

**Comment by jeffreyssmith2nd** [comment]
> Marking as a draft to signify this isn't waiting on another review.
> 
> It isn't clear to me how to proceed with this PR given #11754

Thanks, I do intend to get back to #11754 but am not sure whether this PR will make sense to continue once I have time to think about it.

**Pull request closed without merging**
