### PR TITLE
feat: Add regexp_count function 

### LINKED ISSUE #12079: Add additional regexp function `regexp_count()`
### Is your feature request related to a problem or challenge?

The `regexp_count()` was introduced in PostgreSQL 15 and existed in many similar systems. 

### Describe the solution you'd like

Implement a new UDF function as other `regex_*` functions.

### Describe alternatives you've considered

_No response_

### Additional context

See discussions related https://github.com/apache/datafusion/issues/11946.

### PR DESCRIPTION
**Pull request by Omega359**
## Which issue does this PR close?

Closes #12079 and part of #11946. Followup to PR #12080 by #[xinlifoobar](https://github.com/xinlifoobar) with some additional work (documentation, minor fixes, scalar test fixes).

## Rationale for this change

Add an additional useful regexp function to datafusion

## What changes are included in this PR?

Code, tests, documentation.

## Are these changes tested?

Yes.

## Are there any user-facing changes?

Docs updated to include the new udf.

### CODE REVIEW

**Comment by Omega359** [comment]
Note this PR does not resolve the performance degradation seen in this function as compared to regexp_match or regexp_like. (see https://github.com/apache/datafusion/pull/12080#issuecomment-2316755718 for a benchmark) I believe that should be looked at in a followup ticket.

**Review by alamb — APPROVED** [review]
Thank you @Omega359  -- this looks great. I will merge it in and file a follow on ticket for enhancing its performance

**Comment by alamb** [comment]
FYI @xinlifoobar

**Comment by alamb** [comment]
> Note this PR does not resolve the performance degradation seen in this function as compared to regexp_match or regexp_like. (see [#12080 (comment)](https://github.com/apache/datafusion/pull/12080#issuecomment-2316755718) for a benchmark) I believe that should be looked at in a followup ticket.

Filed https://github.com/apache/datafusion/issues/13011

**Pull request merged**
