### PR TITLE
Remove unused `AggregateOptions` struct and `scalar_update_factor` config setting

### LINKED ISSUE #11998: Remove unused config value `scalar_update_factor`
### Is your feature request related to a problem or challenge?

I noticed while looking at other things I noticed that `scalar_update_factor` is no longer used

https://github.com/search?q=repo%3Aapache%2Fdatafusion%20scalar_update_factor&type=code

### Describe the solution you'd like

Remove the unused config option from the code / comments

### Describe alternatives you've considered

We could leave it in -- it isn't really harming anything

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jc4x4**
## Which issue does this PR close?
Closes #11998 .

## Rationale for this change

Remove unused config in AggregateOptions. Keep the parent struct open in case we need it later. I am fine to removing the option struct.

## Are these changes tested?
no new test. just existing cargo test.

### CODE REVIEW

**Review by findepi — APPROVED** [review]

**Comment by findepi** [comment]
Looking at the build errors, it might be necessary to fully remove the `AggregateOptions` struct now?

**Review by findepi — APPROVED** [review]
LGTM except for docs/source/user-guide/configs.md which i didn't review yet

**Comment by alamb** [comment]
Thank you @jc4x4  and @findepi -- this is a nice cleanup 🧹 

I also marked this PR as an API change as the options structure is changed

**Review by alamb — APPROVED** [review]

**Review by lewiszlw — APPROVED** [review]
👍

**Pull request merged**
