### PR TITLE
Move equivalence fuzz testing to fuzz test binary

### PR DESCRIPTION
**Pull request by alamb**
## Which issue does this PR close?

Part of https://github.com/apache/datafusion/issues/12700

## Rationale for this change
These two tests are fuzz tests and they take 3 orders of magnitude more time to run than the rest of the tests in datafusion-physical-expr

You can see this with
```shell
cargo nextest run -p datafusion-physical-expr --lib
```

```
        PASS [   0.004s] datafusion-physical-expr window::window_expr::tests::test_is_row_ahead
        PASS [   3.604s] datafusion-physical-expr equivalence::ordering::tests::test_ordering_satisfy_with_equivalence_complex_random
        PASS [   4.350s] datafusion-physical-expr equivalence::properties::tests::test_find_longest_permutation_random
        PASS [  15.111s] datafusion-physical-expr equivalence::projection::tests::ordering_satisfy_after_projection_random
```

Let's move the fuzz testing to the fuzz test binary to make normal testing faster

## What changes are included in this PR?

1. Move equivalence fuzz testing to fuzz test binary

After this change the entire test suite in phsyical expr runs in less than a second
```
     Summary [   0.565s] 1327 tests run: 1327 passed, 5 skipped
```

## Are these changes tested?

Yes

## Are there any user-facing changes?

No this is entirely development process

### CODE REVIEW

**Comment by alamb** [comment]
@berkaysynnada  I wonder if you have some time for a review of this PR?

**Comment by berkaysynnada** [comment]
> @berkaysynnada I wonder if you have some time for a review of this PR?

For sure but as I mentioned [here](https://github.com/apache/datafusion/issues/12700#issuecomment-2399036407), I’ve discovered a tricky bug in both the `satisfy()` and `add_ordering()` APIs. I've completed half of the fix so far. I would suggest holding off on this PR until that is resolved, as some of the existing tests will be improved. Once that PR is merged, we can update this PR with a more solid and accurate equivalence mechanism.

**Comment by alamb** [comment]
> > @berkaysynnada I wonder if you have some time for a review of this PR?
> 
> For sure but as I mentioned [here](https://github.com/apache/datafusion/issues/12700#issuecomment-2399036407), I’ve discovered a tricky bug in both the `satisfy()` and `add_ordering()` APIs. I've completed half of the fix so far. I would suggest holding off on this PR until that is resolved, as some of the existing tests will be improved. Once that PR is merged, we can update this PR with a more solid and accurate equivalence mechanism.

Cool -- sounds good

Note this is only a change to move some tests. We can wait until your fix for satisfy/ordering 

I didn't realize you had found a bug

**Review by berkaysynnada — APPROVED** [review]
Based on my findings [there](https://github.com/apache/datafusion/issues/12700#issuecomment-2411134296), we can safely move forward with merging the PR. Thanks @alamb, and sorry for the delay 😞

**Comment by alamb** [comment]
Thanks @berkaysynnada 🙏

**Pull request merged**
