### PR TITLE
Array agg groups accumulator, second attempt

### LINKED ISSUE #10145: Implement GroupsAccumulator for array_agg aggregation function
### Is your feature request related to a problem or challenge?

Based on the article [Aggregating Millions of Groups Fast in Apache Arrow DataFusion](https://arrow.apache.org/blog/2023/08/05/datafusion_fast_grouping/) it's possible to optimise aggregation functions using GroupsAccumulator.

### Describe the solution you'd like

Implement GroupsAccumulator for array_agg aggregation function

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by markusa380**
**Continuation of https://github.com/apache/datafusion/pull/10149**

## Which issue does this PR close?

Closes #10145.
Closes https://github.com/apache/datafusion/pull/10149

## Rationale for this change

See the issue.
## What changes are included in this PR?

GroupsAccumulator for `array_agg` aggregation function for:

* Primitive types
* String type

Not included:
* Accumulating arrays of any level of nesting.

## Are these changes tested?

Extended tests in `aggregate.slt`
## Are there any user-facing changes?

Yes, `IGNORE NULLS` now works with array_agg.

---

I have not yet addressed the comments of the original PR:
* support for LargeUtf8 and Binary (https://github.com/apache/datafusion/pull/10149#discussion_r1573482631)
* benchmark

but instead want to first find out if my approach to null handling is generally valid or not.

The problem with null handling is that this implementation originally ignored null values.
However a test in `aggregate.slt` added meanwhile asserts that it is included.
Now I asked in Discord what approach is correct, to which I was informed that DF is trying to follow PG and Spark.
I thus checked PG and Spark, and as it turns out PG includes nulls while Spark does not:

```
>>> from pyspark.sql.types import StringType
>>> from pyspark.sql.functions import array_agg
>>> data = [("value1",), (None,), ("value3",), (None,), ("value5",)]
>>> df = spark.createDataFrame(data, ["column1"], StringType())
>>> df.count()
5
>>> df.agg(array_agg('column1').alias('r')).collect()
[Row(r=['value1', 'value3', 'value5'])]
```
 
However:
```
-- create
CREATE TABLE EMPLOYEE (
  empId INTEGER PRIMARY KEY,
  name TEXT,
  dept TEXT NOT NULL
);

-- insert
INSERT INTO EMPLOYEE VALUES (0001, 'Clark', 'Sales');
INSERT INTO EMPLOYEE VALUES (0002, 'Dave', 'Accounting');
INSERT INTO EMPLOYEE VALUES (0003, 'Ava', 'Sales');
INSERT INTO EMPLOYEE VALUES (0004, NULL, 'Sales');

-- fetch 
SELECT ARRAY_AGG(name), dept FROM EMPLOYEE group by dept;

```

```
    array_agg     |    dept
------------------+------------
 {Dave}           | Accounting
 {Clark,Ava,NULL} | Sales
(2 rows)
```

So I decided to make everyone happy by adding support for `IGNORE NULLS`

### CODE REVIEW

**Comment by alamb** [comment]
I will try and find time to review this tomorrow. THank you @markusa380

**Comment by alamb** [comment]
I plan to review this tomorrow morning

**Comment by markusa380** [comment]
@alamb I suggest you don't review this now, it looks like there's some major conflict with this:
https://github.com/apache/datafusion/commit/e9e2951abb3c5a0fb3e5d5b8ed75db4ad380c07a
I will have to take some more time to resolve this.

**Review by alamb — COMMENTED** [review]
🤔 The benchmark results apear to be mixed

```
--------------------
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Query        ┃  main_base ┃ array_agg-groups-accumulator-v2 ┃        Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ QQuery 0     │     0.86ms │                          0.87ms │     no change │
│ QQuery 1     │    95.00ms │                         97.90ms │     no change │
│ QQuery 2     │   205.66ms │                        204.51ms │     no change │
│ QQuery 3     │   210.28ms │                        207.06ms │     no change │
│ QQuery 4     │  2239.73ms │                       2191.26ms │     no change │
│ QQuery 5     │  1962.98ms │                       1998.95ms │     no change │
│ QQuery 6     │    87.71ms │                         83.54ms │     no change │
│ QQuery 7     │    97.26ms │                         99.92ms │     no change │
│ QQuery 8     │  3419.52ms │                       3293.90ms │     no change │
│ QQuery 9     │  2406.86ms │                       2392.59ms │     no change │
│ QQuery 10    │   863.62ms │                        865.42ms │     no change │
│ QQuery 11    │   950.55ms │                        959.03ms │     no change │
│ QQuery 12    │  2117.07ms │                       2157.11ms │     no change │
│ QQuery 13    │  4621.89ms │                       4507.84ms │     no change │
│ QQuery 14    │  2842.78ms │                       2888.43ms │     no change │
│ QQuery 15    │  2538.73ms │                       2412.01ms │     no change │
│ QQuery 16    │  6070.69ms │                       5941.28ms │     no change │
│ QQuery 17    │  6010.76ms │                       5856.32ms │     no change │
│ QQuery 18    │ 12305.28ms │                      11909.09ms │     no change │
│ QQuery 19    │   171.37ms │                        175.83ms │     no change │
│ QQuery 20    │  2666.03ms │                       2744.37ms │     no change │
│ QQuery 21    │  3356.16ms │                       3446.94ms │     no change │
│ QQuery 22    │  8498.75ms │                       9339.77ms │  1.10x slower │
│ QQuery 23    │ 21538.59ms │                      22489.59ms │     no change │
│ QQuery 24    │  1312.53ms │                       1368.81ms │     no change │
│ QQuery 25    │  1113.37ms │                       1188.67ms │  1.07x slower │
│ QQuery 26    │  1435.31ms │                       1501.12ms │     no change │
│ QQuery 27    │  3960.65ms │                       4002.54ms │     no change │
│ QQuery 28    │ 30742.95ms │                      28935.23ms │ +1.06x faster │
│ QQuery 29    │  1039.04ms │                       1033.84ms │     no change │
│ QQuery 30    │  2535.98ms │                       2563.35ms │     no change │
│ QQuery 31    │  3294.44ms │                       3302.96ms │     no change │
│ QQuery 32    │ 17200.49ms │                      17215.20ms │     no change │
│ QQuery 33    │  9561.27ms │                       9715.35ms │     no change │
│ QQuery 34    │  9528.20ms │                       9708.13ms │     no change │
│ QQuery 35    │  4253.23ms │                       4191.71ms │     no change │
│ QQuery 36    │   351.77ms │                        351.60ms │     no change │
│ QQuery 37    │   219.39ms │                        238.54ms │  1.09x slower │
│ QQuery 38    │   193.37ms │                        203.92ms │  1.05x slower │
│ QQuery 39    │  1171.07ms │                       1154.55ms │     no change │
│ QQuery 40    │    97.56ms │                         97.61ms │     no change │
│ QQuery 41    │    85.25ms │                         87.23ms │     no change │
│ QQuery 42    │   102.14ms │                        104.12ms │     no change │
└──────────────┴────────────┴─────────────────────────────────┴───────────────┘

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┓
┃ Benchmark Summary                              ┃             ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━┩
│ Total Time (main_base)                         │ 173476.11ms │
│ Total Time (array_agg-groups-accumulator-v2)   │ 173227.96ms │
│ Average Time (main_base)                       │   4034.33ms │
│ Average Time (array_agg-groups-accumulator-v2) │   4028.56ms │
│ Queries Faster                                 │           1 │
│ Queries Slower                                 │           4 │
│ Queries with No Change                         │          38 │
└────────────────────────────────────────────────┴─────────────┘

--------------------
Benchmark tpch.json
--------------------
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┓
┃ Query        ┃ main_base ┃ array_agg-groups-accumulator-v2 ┃       Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━┩
│ QQuery 1     │  333.51ms │                        339.62ms │    no change │
│ QQuery 2     │  126.50ms │                        134.88ms │ 1.07x slower │
│ QQuery 3     │  165.32ms │                        163.39ms │    no change │
│ QQuery 4     │   99.88ms │                        102.41ms │    no change │
│ QQuery 5     │  202.28ms │                        203.27ms │    no change │
│ QQuery 6     │   92.01ms │                         91.54ms │    no change │
│ QQuery 7     │  278.23ms │                        278.15ms │    no change │
│ QQuery 8     │  200.50ms │                        213.43ms │ 1.06x slower │
│ QQuery 9     │  319.18ms │                        324.96ms │    no change │
│ QQuery 10    │  275.71ms │                        284.99ms │    no change │
│ QQuery 11    │  101.88ms │                        103.48ms │    no change │
│ QQuery 12    │  155.04ms │                        158.06ms │    no change │
│ QQuery 13    │  323.16ms │                        332.34ms │    no change │
│ QQuery 14    │  121.68ms │                        120.21ms │    no change │
│ QQuery 15    │  174.75ms │                        176.83ms │    no change │
│ QQuery 16    │   99.55ms │                        110.40ms │ 1.11x slower │
│ QQuery 17    │  315.42ms │                        315.47ms │    no change │
│ QQuery 18    │  446.77ms │                        436.15ms │    no change │
│ QQuery 19    │  200.79ms │                        198.34ms │    no change │
│ QQuery 20    │  195.76ms │                        194.69ms │    no change │
│ QQuery 21    │  343.41ms │                        334.32ms │    no change │
│ QQuery 22    │   76.56ms │                         74.73ms │    no change │
└──────────────┴───────────┴─────────────────────────────────┴──────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┓
┃ Benchmark Summary                              ┃           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━┩
│ Total Time (main_base)                         │ 4647.90ms │
│ Total Time (array_agg-groups-accumulator-v2)   │ 4691.66ms │
│ Average Time (main_base)                       │  211.27ms │
│ Average Time (array_agg-groups-accumulator-v2) │  213.26ms │
│ Queries Faster                                 │         0 │
│ Queries Slower                                 │         3 │
│ Queries with No Change                         │        19 │
└────────────────────────────────────────────────┴───────────┘

**Comment by alamb** [comment]
Marking as draft as I think this PR is no longer waiting on feedback. Please mark it as ready for review when it is ready for another look

**Pull request closed without merging**
