### PR TITLE
Test sort merge join on TPC-H benchmark

### PR DESCRIPTION
**Pull request by Dandandan**
## Which issue does this PR close?

Closes https://github.com/apache/datafusion/issues/13573

## Rationale for this change
More testing for sort merge join

## What changes are included in this PR?

* Split tests into plans and answers
* Test answers with `datafusion.optimizer.prefer_hash_join = false`

### CODE REVIEW

**Review by comphead — COMMENTED** [review]
Thanks @Dandandan I'll check this later. 

Earlier there was introduced a env var to run TPCH benches with SMJ enabled.

https://github.com/apache/datafusion/pull/10092

**Review by comphead — COMMENTED** [review]
Thanks @Dandandan it looks great. One question, is it supposed to have an SMJ in expected plans? I picked some plan files and haven't noticed SMJ plan nodes there

**Comment by Dandandan** [comment]
> Thanks @Dandandan it looks great. One question, is it supposed to have an SMJ in expected plans? I picked some plan files and haven't noticed SMJ plan nodes there

No, they aren't supposed to, I only moved the existing hash join plans and tested both hash join as sort merge  join for answers.

**Review by comphead — APPROVED** [review]
lgtm thanks @Dandandan

**Comment by Dandandan** [comment]
Thanks for the review @comphead

**Pull request merged**
