### PR TITLE
feat(substrait): AggregateRel grouping_expressions support

### LINKED ISSUE #12957: [substrait] handle AggregateRel grouping_expressions field
### Is your feature request related to a problem or challenge?

https://github.com/apache/datafusion/pull/12863 updated DataFusion with changes from Substrait 0.58.0

The Substrait changes included https://github.com/substrait-io/substrait/pull/706, which added a new `grouping_expressions` field to the AggregateRel.

### Describe the solution you'd like

DataFusion should be updated to correctly read and write this new field, in line with the updated spec.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by akoshchiy**
## Which issue does this PR close?

Closes #12957.

## What changes are included in this PR?
Added support of `grouping_expressions` field in `AggregateRel`. Deprecated support is still here -  producer fills both fields, and consumer tries to parse deprecated field at first.

## Are these changes tested?
Yes.

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @akoshchiy 

@vbarua  can you double check this as well?

**Comment by vbarua** [comment]
I can put this on my queue for next week.

**Comment by alamb** [comment]
I am going to merge this PR to keep the code flowing. If there are any additional issues found as part of @vbarua 's review we can address them as a follow on PR.

Thanks again @akoshchiy and @vbarua

**Review by vbarua — COMMENTED** [review]
This looks pretty reasonable to me 🙂

**Pull request merged**
