### PR TITLE
Rewrite `CommonSubexprEliminate` to avoid copies using TreeNode

### PR DESCRIPTION
**Pull request by alamb**
WIP -- still has many more copies to remove

## Which issue does this PR close?

Part of https://github.com/apache/arrow-datafusion/issues/9637

related to https://github.com/apache/datafusion/issues/9873

## Rationale for this change

Let's make planning faster by not copying so much in the optimizer using the new TreeNode API.

## What changes are included in this PR?

1. See PR subject

Note this pass still leaves a lot to be desired in terms of copying Exprs / making strings but it is much better now. Fixing up the additional copies is tracked with https://github.com/apache/arrow-datafusion/issues/9873

## Are these changes tested?
Functional: existing tests
Performance: TBD

### CODE REVIEW

**Comment by peter-toth** [comment]
@alamb, can I take this PR and rebase it on the latest `main`? It would be better to refactor CSE rule to use `rewrite()` before I can finish my https://github.com/apache/datafusion/pull/10473.

**Comment by peter-toth** [comment]
Sure, please work on it if you have some time during the weekend as I can't do it earlier than next week.
Let me know how it goes and I can take this next week if you don't have time.

**Comment by alamb** [comment]
> Sure, please work on it if you have some time during the weekend as I can't do it earlier than next week. Let me know how it goes and I can take this next week if you don't have time.

Will do -- thank you

**Comment by alamb** [comment]
Superceded by https://github.com/apache/datafusion/pull/10835, will continue work there

**Pull request closed without merging**
