### PR TITLE
Cleanup `WindowExpr` and `AggregateExpr` trait

### PR DESCRIPTION
**Pull request by lewiszlw**
## Which issue does this PR close?

Closes #.

## Rationale for this change

Found some methods are never used in WindowExpr and AggregateExpr trait, as they are not public traits, so just remove them.

### CODE REVIEW

**Comment by berkaysynnada** [comment]
We use these methods in our fork. If there is no harm, we would prefer to keep them.

**Comment by lewiszlw** [comment]
We might eventually delete entire `AggregateExpr ` trait (https://github.com/apache/datafusion/issues/11810).

**Comment by berkaysynnada** [comment]
I agree that `AggregateExpr` should be deleted, but I prefer to remove it at one shot. You are also removing more here.

**Comment by lewiszlw** [comment]
I could remove `WindowExpr` trait change in this pr. 

Removing `AggregateExpr` trait at one shot will result a huge pr, it's hard for reviewing.

**Review by ozankabak — COMMENTED** [review]
This would get the code in a state that breaks some downstream users (including us). Let's proceed one by one -- let's start off by focusing on removing `AggregateExpr`. We will help with reviewing.

If you want to do this in small PRs and make this the first step, you can start off by moving `all_expressions` and `with_new_expressions` APIs to `AggregateFunctionExpr`. Thanks

**Comment by lewiszlw** [comment]
Alright, I'll try to remove `AggregateExpr` trait in one pr.

**Pull request closed without merging**
