### PR TITLE
Enable `clone_on_ref_ptr` clippy lint on physical-expr crate

### PR DESCRIPTION
**Pull request by lewiszlw**
## Which issue does this PR close?

part of https://github.com/apache/datafusion/issues/11143.

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thanks again @lewiszlw

**Comment by alamb** [comment]
Since this PR is likely to accumulate merge conflicts over time, I think we should probably merge it in relatively soon

I took the liberty of merging up from main and resolving a bunch of conflicts

cc @ozankabak what do you think?

**Comment by ozankabak** [comment]
Let's merge this today. We can do the other big PR towards the end of the next week to give everyone some time in between.

**Comment by alamb** [comment]
Thanks again @lewiszlw and @ozankabak

**Pull request merged**
