### PR TITLE
doc-gen: migrate builtin scalar functions documentation to attribute based

### PR DESCRIPTION
**Pull request by Chen-Yuan-Lai**
## Which issue does this PR close?

Closes #13671 

## What changes are included in this PR?

As discussed in #13671 , this PR will migrate the builtin scalar functions documentation that currently support migration.

### CODE REVIEW

**Comment by alamb** [comment]
Thank you @Chen-Yuan-Lai  -- this looks epic!

Given the size of this PR I suspect it will be hard to find time to review and also hard to keep up to date (it will likely accumulate conflicts quickly) as it already has a substantial number:
Screenshot 2024-12-22 at 8 16 51 AM

Would it be possibel to break it down into a number of smaller PRs (maybe one PR for each `datafusion-functions`, `datafusion-functions-array`, etc?

**Comment by Chen-Yuan-Lai** [comment]
@alamb Sure! I'll break it down into smaller PRs. Thank you for the suggestion.

**Comment by Omega359** [comment]
I can help with reviewing the smaller PR's once they are submitted

**Comment by comphead** [comment]
Great work 💪 thanks @Chen-Yuan-Lai

**Comment by alamb** [comment]
Marking as draft as I think this PR is no longer waiting on feedback. Please ping us on the other PRs 🙏 

Thanks aain @Chen-Yuan-Lai

**Comment by comphead** [comment]
should we close it @Chen-Yuan-Lai ?

**Pull request closed without merging**
