### PR TITLE
Implement user defined planner for extract

### LINKED ISSUE #11220: Implement user defined planner for `date_part`
### Is your feature request related to a problem or challenge?

As discussed in #11207 The idea is to move hardcoded the `date_part` operator to function in the parser step, which is currently handled in the optimizer step. We need to implement user-defined parser mechanisms to enable more flexible SQL planning.

### Describe the solution you'd like

_No response_

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by xinlifoobar**
## Which issue does this PR close?

Part of #11207 and closes #11220

### CODE REVIEW

**Review by jayzhan211 — APPROVED** [review]
👍

**Review by alamb — APPROVED** [review]
I merged this PR up from main to resolve some conflicts

**Comment by alamb** [comment]
Thanks again @xinlifoobar

**Comment by Omega359** [comment]
I just reset my branch with upstream main just now and I'm getting this in 4 of my tests:

```
---- network_time_parsing_should_work::case_2 stdout ----
Error: Result failed: Unable to transform sql expression 'extract(year FROM transaction_date)' to datafusion Expr: Some(NotImplemented("Extract not supported by UserDefinedExtensionPlanners: [Literal(Utf8(\"YEAR\")), Column(Column { relation: None, name: \"transaction_date\" })]"))
```
Is there some required changes to supporting code to facilitate the changes in this issue?

**Comment by Omega359** [comment]
Adding this clause to the plan_to_sql.rs:roundtrip_expr() test showcases the issue:

```
(
            TableReference::bare("person"),
            r#"extract(year from "2024-12-30"::date)"#,
            r#"fixme"#,
        ),
```

**Comment by Omega359** [comment]
The issue boils down to SqlToRel::new_with_options(..) not setting the planners. Unfortunately, I can't find a way to retrieve the list of planners set on the context to set them myself - I'll file a ticket for that shortly.

**Comment by alamb** [comment]
> The issue boils down to SqlToRel::new_with_options(..) not setting the planners. Unfortunately, I can't find a way to retrieve the list of planners set on the context to set them myself - I'll file a ticket for that shortly.


issue / PR: https://github.com/apache/datafusion/pull/11296 / https://github.com/apache/datafusion/issues/11294

**Pull request merged**
