### PR TITLE
fix: add missing `NotExpr::evaluate_bounds`

### PR DESCRIPTION
**Pull request by crepererum**
## Which issue does this PR close?
\-

## Rationale for this change
Support more expressions for range/bounds analysis.

## What changes are included in this PR?
`NotExpr::evaluate_bounds`, which just forwards to `Interval::not`.

## Are these changes tested?
\-

## Are there any user-facing changes?
\-

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
Is it possible to add a test for this change?

**Review by berkaysynnada — APPROVED** [review]
LGTM, better after https://github.com/apache/datafusion/pull/13082#pullrequestreview-2390828994

**Comment by crepererum** [comment]
> Is it possible to add a test for this change?

Do we have a test collection for this interface? Because just adding a unit test within this module sounds like "you just test that it is forwarded at all", which IMHO has limited value.

**Comment by alamb** [comment]
> > Is it possible to add a test for this change?
> 
> Do we have a test collection for this interface? Because just adding a unit test within this module sounds like "you just test that it is forwarded at all", which IMHO has limited value.

I found https://github.com/apache/datafusion/blob/9355f4a5c7cb99df318ea98316cafc9b0494316f/datafusion/physical-expr/src/expressions/negative.rs#L226-L225

I'll add a test to this PR similarly

**Comment by alamb** [comment]
I took the liberty of adding a test to this PR and merging up from main

**Pull request merged**
