### PR TITLE
Enhance table scan unparsing to avoid unnamed subqueries.

### PR DESCRIPTION
**Pull request by goldmedal**
## Which issue does this PR close?

It's a follow-up PR of #12896 

## Rationale for this change
from https://github.com/apache/datafusion/pull/12896#issuecomment-2408609989

## Are these changes tested?
Enhance the original tests

### CODE REVIEW

**Review by alamb — APPROVED** [review]
This makes sense to me -- thank you @goldmedal 

Perhaps @phillipleblanc and @sgrebnov  have some time to review this as well

**Comment by alamb** [comment]
Let's merge this in and we can address any feedback as a follow on PR

**Comment by phillipleblanc** [comment]
Whoops, I had pending feedback that I didn't submit in time.

**Comment by alamb** [comment]
> Whoops, I had pending feedback that I didn't submit in time.

I do that far more often than I would like to admit. Maybe it is a good excuse for a follow on PR

**Pull request merged**
