### PR TITLE
Refactor regexplike signature

### PR DESCRIPTION
**Pull request by jiashenC**
## Which issue does this PR close?

Close some tasks in #13301.

## What changes are included in this PR?

Simplify function signature.

## Are these changes tested?

Added more tests for implicit casting.

## Are there any user-facing changes?

No

### CODE REVIEW

**Comment by jiashenC** [comment]
@jayzhan211, I made some progress first for the `RegExpLike` function. In the original issue, you mentioned the signature can be replaced with `Signature::string(2, Volatility::Immutable)`, but I do see this function can also accept 3 arguments. And this will fail tests like `dataframe::dataframe_functions::test_fn_regexp_like`. I wonder if I misunderstood something here?

**Comment by jayzhan211** [comment]
> @jayzhan211, I made some progress first for the `RegExpLike` function. In the original issue, you mentioned the signature can be replaced with `Signature::string(2, Volatility::Immutable)`, but I do see this function can also accept 3 arguments. And this will fail tests like `dataframe::dataframe_functions::test_fn_regexp_like`. I wonder if I misunderstood something here?

Similar to StringToArray, you can use `one_of`
```rust
signature: Signature::one_of(
                vec![
                    TypeSignature::Uniform(2, vec![Utf8, LargeUtf8]),
                    TypeSignature::Uniform(3, vec![Utf8, LargeUtf8]),
                ],
                Volatility::Immutable,
            ),
```

**Comment by jiashenC** [comment]
@jayzhan211 thanks for the reply! I mark this as ready for review.

**Comment by jayzhan211** [comment]
> @jayzhan211 thanks for the reply! I mark this as ready for review.

You can run `cargo test --test sqllogictests` and `./dev/rust_lint.sh` to cleanup CI

**Comment by alamb** [comment]
There appears to be a CI test failure in the examples were some queries no longer work

**Comment by alamb** [comment]
Thank you for this contribution @jiashenC

**Comment by Omega359** [comment]
I think the CI failures are a type casting issue. There are two rows in the example that have `4000` as the values that I think are not being coerced to strings as they should be.

```
 Error: Plan("Internal error: Failed to match any signature, errors: Error during planning: The signature expected 3 arguments but received 2,Error during planning: The signature expected NativeType::String but received NativeType::Int64.\nThis was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker No function matches the given name and argument types 'regexp_like(Utf8, Int64, Utf8)'. You might need to add explicit type casts.\n\tCandidate functions:\n\tregexp_like(String(2))\n\tregexp_like(String(3))")
 ```
 
 Input data for the example: https://github.com/apache/datafusion/blob/main/datafusion/physical-expr/tests/data/regex.csv

**Comment by alamb** [comment]
(sorry I accidnetally closed the PR)

**Review by jayzhan211 — APPROVED** [review]

**Comment by jayzhan211** [comment]
Thanks @jiashenC @alamb @Omega359

**Pull request merged**
