### PR TITLE
Support multi extension codecs for `AsExecutionPlan` trait

### PR DESCRIPTION
**Pull request by lewiszlw**
## Which issue does this PR close?

Closes #.

## Rationale for this change

Execution plan tree might have different node from different crates, for example `ShuffleWriterExec` from `datafusion-ballista` and `DeltaScan` from `deltalake`, these crates both provide `PhysicalExtensionCodec`.
```
ShuffleWriterExec
    ProjectionExec
       ...
          DeltaScan
```
We should be able to serialize/deserialize this case.

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
Rather than changing the API, I wonder if we could instead provide an example of how to make your own composeable codec

Something like

```rust
/// A PhysicalExtensionCodec that tries one of multiple inner codecs 
/// until one works
struct ComposedCodec {
  codecs: Vec<Arc<dyn PhysicalExtensionCodec>>
}

impl PhysicalExtensionCodec for ComposedCodec
    // Required methods
    fn try_decode(
        &self,
        buf: &[u8],
        inputs: &[Arc<dyn ExecutionPlan>],
        registry: &dyn FunctionRegistry,
    ) -> Result<Arc<dyn ExecutionPlan>> {
      let mut last_e = None;
      for codec in self.codecs.iter() {
       match codec.try_decode(buf, inputs, registry) {
         Ok(plan) => return Ok(plan),
        // remember error
         Err(e) => last_e = Some(e),
       }
     return Err(last_e.unwrap())  
    }
...
}

**Comment by lewiszlw** [comment]
Looks great. I'll give it a try later.

**Comment by alamb** [comment]
Marking as draft as I don't think this PR is waiting on more feedback and I am trying to clear out the remaining reviews

**Comment by lewiszlw** [comment]
Closed in favor of https://github.com/apache/datafusion/pull/11095.

**Pull request closed without merging**
