### PR TITLE
Bump MSRV to 1.78

### PR DESCRIPTION
**Pull request by comphead**
## Which issue does this PR close?

According to https://releases.rs the 1.81 has been released recently

By policy we should have been migrating to 1.77 but this release had too many hotfixes, so it probably safer to go with
1.78 Rust compiler that has been released on May 2

Closes #.

Depends on #12402

### CODE REVIEW

**Comment by alamb** [comment]
1.78 was released on 2 May, 2024 it seems: https://releases.rs/docs/1.78.0/

that means to follow our [policy of 6 months](https://github.com/apache/datafusion?tab=readme-ov-file#rust-version-compatibility-policy) we need to wait for Nov 2, 2024 I think 🤔 

I personally would be fine with a less stringent policy on MSRV (e.g. 3 months or 3 major rust versions or something) but as written I think this PR doesn't follow the policy

**Comment by comphead** [comment]
> 1.78 was released on 2 May, 2024 it seems: https://releases.rs/docs/1.78.0/
> 
> that means to follow our [policy of 6 months](https://github.com/apache/datafusion?tab=readme-ov-file#rust-version-compatibility-policy) we need to wait for Nov 2, 2024 I think 🤔
> 
> I personally would be fine with a less stringent policy on MSRV (e.g. 3 months or 3 major rust versions or something) but as written I think this PR doesn't follow the policy

Thanks @alamb the DF MSRV policy perhaps should be revised. it reads as 6 months which supports 3-4 most recent versions. 

I feel now the Rust release cadences are shorter so most recent 4 versions, (1.78, 1.79, 1.80, 1.81) are fit into 4 months.

May be want to rephrase the policy saying supporting last 4 versions or 4 months whatever is longer?

**Comment by alamb** [comment]
> May be want to rephrase the policy saying supporting last 4 versions or 4 months whatever is longer?

Sounds  very reasonable to me

I suggest we propose that as a PR and make sure everyone is cool with it. (like we can post a note to the dev email list and slack)

It might be good to wait for the 42.0.0 (#11902)  release  to out before making the change too

**Comment by comphead** [comment]
> > May be want to rephrase the policy saying supporting last 4 versions or 4 months whatever is longer?
> 
> Sounds very reasonable to me
> 
> I suggest we propose that as a PR and make sure everyone is cool with it. (like we can post a note to the dev email list and slack)
> 
> It might be good to wait for the 42.0.0 (#11902) release to out before making the change too so we have some bake time

Refined the policy https://github.com/apache/datafusion/pull/12402

**Comment by comphead** [comment]
should we proceed with this PR?

**Comment by alamb** [comment]
I recommend waiting until tomorrow (after 42 release is cut - https://github.com/apache/datafusion/issues/11902) and then merging it in unless anyone objects

**Review by findepi — APPROVED** [review]
thanks for doing this

it would be nice if the MSRV was defined in one place

**Review by alamb — APPROVED** [review]
Thanks @comphead  -- I think this looks good to me and we have left it open enough for a discussion from my perspective. Let's do it

**Comment by alamb** [comment]
Marking PR as api change to get it a little more attention in the release notes

**Comment by alamb** [comment]
I merged up from main to resolve a conflict

**Pull request merged**
