### PR TITLE
Minor: Move aggregate variance to slt

### LINKED ISSUE #10384: Port aggregate test to sqllogictest
### Is your feature request related to a problem or challenge?

There are many rust test that exists in aggregate functions. Moving them to sqllogictest is easier to maintain and avoid additional testing functions like `generic_test_op`, `assert_string_aggregate`, `assert_aggregate`, `assert_error_bounds`, and so on. It also makes #8708 a lot easier.

#10382 is an example of how tests are moved to.

I think most of them are Good first issue:
- [X] Sum #10382
- [X] Count #10383 
- [X] average #10401 
- [X] #10457 
- [ ] min_max
- [ ] array_agg
- [ ] correlation
- [ ] median
- [ ] stddev
- [ ] variance

### Describe the solution you'd like

Port rust test in `datafusion/physical-expr/src/aggregate/tdigest.rs` to `datafusion/sqllogictest/test_files/aggregate.slt`

We can just add the test to `aggregate.slt` even if there is a duplicated test case to make the review easier.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by marvinlanhenke**
## Which issue does this PR close?

Close #10384

## What changes are included in this PR?

- moved tests to aggregate.slt

### CODE REVIEW

**Comment by marvinlanhenke** [comment]
@jayzhan211 PTAL. Also I think this was the last one? perhaps #10384 can be closed then?

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @marvinlanhenke

**Review by jayzhan211 — APPROVED** [review]
👍

**Comment by jayzhan211** [comment]
> @jayzhan211 PTAL. Also I think this was the last one? perhaps #10384 can be closed then?

Yes, it seems like the last one

**Comment by jayzhan211** [comment]
Thanks @marvinlanhenke @alamb

**Pull request merged**
