### PR TITLE
fix(CLI): can not create external tables with format options

### LINKED ISSUE #10737: CLI cannot create external tables with format options
### Describe the bug

It raised an error for such a case: 
> Invalid or Unsupported Configuration: Specify a format for TableOptions

### To Reproduce

```sh
DataFusion CLI v38.0.0

> CREATE EXTERNAL TABLE aggregate_test_100 (
  c1  VARCHAR NOT NULL,
  c2  TINYINT NOT NULL,
  c3  SMALLINT NOT NULL,
  c4  SMALLINT,
  c5  INT,
  c6  BIGINT NOT NULL,
  c7  SMALLINT NOT NULL,
  c8  INT NOT NULL,
  c9  BIGINT UNSIGNED NOT NULL,
  c10 VARCHAR NOT NULL,
  c11 FLOAT NOT NULL,
  c12 DOUBLE NOT NULL,
  c13 VARCHAR NOT NULL
)
STORED AS csv
LOCATION '../testing/data/csv/aggregate_test_100.csv'
OPTIONS('format.has_header' 'true');

Invalid or Unsupported Configuration: Specify a format for TableOptions
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jonahgao**
## Which issue does this PR close?

Closes #10737.

## Rationale for this change

When setting format options for `TableOptions`,
https://github.com/apache/datafusion/blob/09dde27be39ad054f85dfb5c37b7468a3f68d652/datafusion-cli/src/exec.rs#L376

the `current_format` of `TableOptions` must already exist, which means [set_file_format](https://github.com/apache/datafusion/blob/09dde27be39ad054f85dfb5c37b7468a3f68d652/datafusion-cli/src/exec.rs#L374) must be called with a non-none file type first.
https://github.com/apache/datafusion/blob/09dde27be39ad054f85dfb5c37b7468a3f68d652/datafusion/common/src/config.rs#L1185-L1187

## Are these changes tested?
Yes
## Are there any user-facing changes?
No

### CODE REVIEW

**Comment by berkaysynnada** [comment]
Good catch 👍🏻 This explicit setup may not be very user-friendly, but it's necessary since we accept file formats directly from `CreateExternalTable` rather than from `OPTIONS`.

**Review by comphead — APPROVED** [review]
lgtm thanks @jonahgao 
💪

**Review by alamb — APPROVED** [review]
Thank you @jonahgao  🙏

**Comment by jonahgao** [comment]
Thanks for the review @berkaysynnada @comphead @alamb

**Pull request merged**
