### PR TITLE
Minor: Avoid emitting empty batches in partial sort

### PR DESCRIPTION
**Pull request by berkaysynnada**
## Which issue does this PR close?

Closes #.

## Rationale for this change

PartialSort could still generate empty batches after the exhaustion of its input. That is avoided, and debug_assert!() is moved to the actual return point.

### CODE REVIEW

**Review by ozankabak — APPROVED** [review]
LGTM

**Comment by alamb** [comment]
FYI @comphead  and @korowa

**Review by comphead — APPROVED** [review]
lgtm thanks @berkaysynnada from what i remember we got multiple of such paths where empty batch returned and remaining part of plan executed for nothing

**Comment by berkaysynnada** [comment]
> lgtm thanks @berkaysynnada from what i remember we got multiple of such paths where empty batch returned and remaining part of plan executed for nothing

We need to avoid all those paths

**Comment by ozankabak** [comment]
This is already reviewed by 3 people and is a fairly easy change, so I will go ahead and merge it

**Pull request merged**
