### PR TITLE
Use stabalized aws-sdk and clap versions in `datafusion-cli`

### PR DESCRIPTION
**Pull request by satyakommula96**
## Which issue does this PR close?

with the latest changes from the main branch and open a new pull request

previous #8681 

Closes #.

## What changes are included in this PR?

Bump datafusion-cli dependencies
use stabilized version aws-sdk 1.x.x (https://www.infoworld.com/article/3711271/aws-delivers-aws-sdk-for-rust.html)
use latest clap version

## Are these changes tested?

yes

### CODE REVIEW

**Comment by satyakommula96** [comment]
please review @alamb @comphead

**Review by alamb — APPROVED** [review]
Thank you @satyakommula96  -- I also merged up from main to fix a conflict in this PR and to trigger the CI.

**Comment by alamb** [comment]
🤔  CI seems to have failed here: https://github.com/apache/arrow-datafusion/actions/runs/8327813127/job/22786403043?pr=9659

```
Run cargo msrv verify
Fetching index
Verifying the Minimum Supported Rust Version (MSRV) for toolchain x86_64-unknown-linux-gnu
Using check command cargo check
   Failed check command cargo check didn't succeed
Crate source was found to be incompatible with its MSRV '1.72.1', as defined in '/__w/arrow-datafusion/arrow-datafusion/datafusion-cli/Cargo.toml'
Error: Process completed with exit code 1.
```

**Comment by alamb** [comment]
Looks like we never formalized the MSRV discussion in https://github.com/apache/arrow-datafusion/issues/9082 -- I will make a PR to do so now

**Pull request closed without merging**
