### PR TITLE
Allow using dictionary arrays as filters

### LINKED ISSUE #12380: Dictionary columns (with a `Boolean` values) can't be used directly as filters
### Describe the bug

Running

```sql
select count(*) v from dicts where json_contains(json_data, str_key2)
```
Where `json_contains` returns a `Dictionary(UInt32, Boolean)` (as of https://github.com/datafusion-contrib/datafusion-functions-json/pull/39), results in:

```
called `Result::unwrap()` on an `Err` value: Plan("Cannot create filter with non-boolean predicate 'json_contains(dicts.json_data, dicts.str_key2)' returning Dictionary(UInt32, Boolean)")
```

If I change the sql to

```sql
select count(*) v from dicts where json_contains(json_data, str_key2) is true
```

Works fine.

Is this intended or a mistake?

### To Reproduce

_No response_

### Expected behavior

I would have assumed it should just work, but perhaps I'm mistaken?

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by adriangb**
Fixes #12380

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
It seems to me that a `DictionaryArray` with Boolean values is likely to only ever perform worse than a native `BooleanArray` 

The rationale is that each element of a DictionaryArray takes at least 1 byte (for the index into the dictionary when indexed by `Int8`/`UInt8`) where each element in a `BooleanArray` consumes a single *bit*

So while I think this code is fine and we could merge it, the feature seems suspicious to me 🤔

**Comment by adriangb** [comment]
I agree, I was thinking the same thing. The context is a kernel that operates on arrays, the output of which may or may not be used in a filter. I guess the kernel could do the conversion but I figured if we can support it here Filter could do the conversion internally (if it makes sense, maybe it already is?)

**Comment by alamb** [comment]
> 
I agree, I was thinking the same thing. The context is a kernel that operates on arrays, the output of which may or may not be used in a filter. I guess the kernel could do the conversion but I figured if we can support it here Filter could do the conversion internally (if it makes sense, maybe it already is?)


I think this conversion is typically done in coercion -- like in https://docs.rs/datafusion/latest/datafusion/logical_expr/type_coercion/binary/fn.comparison_coercion.html

(which basically means DataFusion would apply a cast internally to cast `Dictionary(*, Boolean)` --> `Boolean`

**Review by alamb — APPROVED** [review]
I think it makes sense to allow Dictionary as a filter (even though I think subsequent processing will effectively cast it to a `BooleanArray`)

**Comment by Dandandan** [comment]
I think that functions like `json_contains` shouldn't create a `DictionaryArray` but rather a `BooleanArray` directly (so no conversion is needed).

**Comment by adriangb** [comment]
Yeah I agree, that's probably the better way to do things _but_ does it hurt to also add this support? I guess it could be a performance foot gun to allow this, although I don't know how bad it would be. The alternative of not implementing this is the foot gun of: you implement a kernel, write some tests for it but _not_ this specific case and then discovering via a user reporting a bug that DataFusion has this limitation and have to go patch your kernel to protect against this case.

**Comment by alamb** [comment]
> Yeah I agree, that's probably the better way to do things _but_ does it hurt to also add this support? I guess it could be a performance foot gun to allow this, although I don't know how bad it would be.

Yeah, I think the potential issue would be that your code creates these `DictionaryArray`s of `Boolean` that is quite a bit slower if you had created `BooleanArray` directly. 

If DataFusion errors, then you know to go try and fix it, but if it doesn't error, then you may never know

That being said, I think this particular change is fine and that we could merge it for the reasons discussed above.

**Comment by alamb** [comment]
Thanks again @adriangb and @Dandandan

**Comment by samuelcolvin** [comment]
See https://github.com/apache/arrow-rs/issues/6409 which is closely related

**Pull request merged**
