### PR TITLE
Minor: add `Window::try_new_with_schema` constructor

### PR DESCRIPTION
**Pull request by sadboy**
## Which issue does this PR close?

Closes N/A

## Rationale for this change

This change makes the `Window` node API more uniform with other `LogicalPlan` nodes, which all expose both `try_new` and `try_new_with_schema` constructors.

## What changes are included in this PR?

New method `Window::try_new_with_schema`

## Are these changes tested?

Covered by existing tests.

## Are there any user-facing changes?

No.

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
Also I wonder if we could update at least one callsite to use `try_new_with_schema` so we get some test coverage 🤔

**Comment by sadboy** [comment]
> if we could update at least one callsite to use `try_new_with_schema` so we get some test coverage

`Window::try_new` actually calls `try_new_with_schema` to do the work, that's why I didn't bother adding new tests. Do you think that's sufficient coverage?

**Comment by alamb** [comment]
> `Window::try_new` actually calls `try_new_with_schema` to do the work, that's why I didn't bother adding new tests. Do you think that's sufficient coverage?

I think it is reasonable enough  🤔 . It might be good as a follow on PR to add another external callsite so that we don't accidentally mess up this API by accident)

**Comment by alamb** [comment]
Thanks again @sadboy  -- We can add additional documentation as a follow on PR

**Pull request merged**
