### PR TITLE
Remove ScalarValue::Dictionary

### PR DESCRIPTION
**Pull request by findepi**
`ScalarValue` should be a container for a single nullable logical type and should not be concerned by various physical encodings used in arrays. It doesn't involve arrays even as part of internal representation (like arrow `Scalar` does).

Remove `Dictionary` option from the `ScalarValue`. Note that `ScalarValue` doesn't have mapping for RLE arrays, while there are very similar type to dictionaries.

Having `ScalarValue` follow complexity of various physical representations poses a burden on UDF implementers. They need to handle all equivalent scalar values.

### CODE REVIEW

**Comment by notfilippo** [comment]
Just posting it here for reference as this PR overlaps with some of the work in this other PR: https://github.com/apache/datafusion/pull/11978

**Comment by notfilippo** [comment]
Thanks @findepi 

> Do you think it could help to have it land faster if it was done in small steps?

Definitely as it would make it easier to review. I opened the PR just to make sure that the same approach would be applicable as we remove more types (which i presume was very successful as we were able to identify some key issues that need attention). Once we reach consensus I was planning splitting my work into smaller PRs.

> In any case, how can i help with this work?

Would really appreciate to get more eyes on my PR :)

**Comment by alamb** [comment]
> Thanks @findepi
> 
> > Do you think it could help to have it land faster if it was done in small steps?
> 
> Definitely as it would make it easier to review. I opened the PR just to make sure that the same approach would be applicable as we remove more types (which i presume was very successful as we were able to identify some key issues that need attention). Once we reach consensus I was planning splitting my work into smaller PRs.

From my point of view, there is pretty broad consensus that having ScalarValue mirror the physical representation (e.g. `ScalarValue::Utf8`, `ScalarValue::UtfView`, `ScalarValue::LargeUtf8`) is non ideal

The challenge is, as @findepi  implies, figuring out how to make the changes incrementally (both to keep the change possible to review as well as to give downstream consumers time to absorb the change)

**Comment by alamb** [comment]
> For example when removing ScalarValue::Dictionary I did some non-obvious chances that require actual review.

BTW I think the most important potential concern for this change is that arrays will be cast at runtime (e.g. when comparing a `Dictionary(String)` column and a `String` scalar, it is very important that the Dictionary column is not cast to a `StringArray`

**Review by alamb — COMMENTED** [review]
Thank you @findepi and @notfilippo . TLDIR is I think this is absolutely the right direction. 

Sorry for the delay in reviewing.

> To me those are properties of physical representation of series of values, that are not attributes of a single value, so ScalarValue doesn't have to be concerned about them.

I agree

>  I think ScalarValue reflects some of them because we expect it to define type, and we expect type to sometimes define physical representation. This is blurry.

I also agree it is blurry. I believe that DataFusion uses the Arrow type system for logical types initially for convenience -- at that time there was only `Dictionary` (REE, StringView were added later). So while it was annoying to handle one special case (Dictionary), it was manageable compared to all the other stuff going on

In my opinion if DataFusion was being implemented again starting today, it would not use Arrow::DataType directly for its logical type system but instead would have a more generic `LogicalDataType` similarly to what is proposed by @notfilippo 

As you show in this PR, even the one special case for `Dictionary` is quite substantial. Also our experience adding support for StringView involved many changes that have nothing to do with the physical representation (https://github.com/apache/datafusion/pull/12503 from @my-vegetable-has-exploded just this morning is a good example)



> if we want scalar value to represent all possible aspects of array representation then arrow's builtin Scalar seems to be ready for that.

Yes, I agree. The reason that DataFusion doesn't use the arrow [Datum](https://docs.rs/arrow/latest/arrow/array/trait.Datum.html) yet is twofold from my perspective:
1. `ScalarValue` predates `Datum` so `Datum` wasn't an option 
2. `Datum` (single row array) is quite a bit less efficient than `ScalarValue` (e.g. a single row StringArray will have several allocations for buffers, offsets, etc)

**Comment by jayzhan211** [comment]
@findepi Note that ScalarValue in #11978 is not the final state of #11513, it is a step toward the #11513. I think we could have LogicalType without any Arrow's DataType contained in it in the future, and it would be the ideal type what you mentioned. `ScalarValue` will be a `physical type` similar to `Arrow's Scalar` but optimized for native type like (i32, i64).

**Comment by findepi** [comment]
> 2\. `Datum` (single row array) is quite a bit less efficient than `ScalarValue` (e.g. a single row StringArray will have several allocations for buffers, offsets, etc)

for function execution that sounds like a dead end.

in my free time i am trying to cook something for function calls.
that's where my interest in ScalarValue various options comes from

**Comment by findepi** [comment]
@notfilippo @alamb do you see any value in this PR, or should we just close it?

**Comment by alamb** [comment]
> @notfilippo @alamb do you see any value in this PR, or should we just close it?

I am not sure about the code in the PR, but the idea seems like a step in the right direction (after https://github.com/apache/datafusion/pull/12536)

**Pull request closed without merging**
