### PR TITLE
Port / Add Documentation for `VarianceSample` and `VariancePopulation`

### PR DESCRIPTION
**Pull request by alamb**
~Draft as it builds on https://github.com/apache/datafusion/pull/12747~

## Which issue does this PR close?
Part of https://github.com/apache/datafusion/issues/12740

## Rationale for this change

Automatically generating documentation has several benefits as listed on https://github.com/apache/datafusion/issues/12740

## What changes are included in this PR?

1. Port documentation

### CODE REVIEW

**Comment by alamb** [comment]
I also used this PR as a way to double check the new CI check works -- here is an example of it failing: https://github.com/apache/datafusion/actions/runs/11166713917/job/31041794120?pr=12742

**Review by comphead — APPROVED** [review]
lgtm, thanks @alamb 
@Omega359 I'm thinking if we can build the same doc from using rustdoc or rust attributes 🤔

**Comment by Omega359** [comment]
> @Omega359 I'm thinking if we can build the same doc from using rustdoc or rust attributes 🤔

Absolutely we could, and I actually toyed with rustdoc approach at first. My main concern with that is that I envision this is useful outside of just the website documentation and for that I would believe we want the docs to be as easily accessible as possible. I can't think of more accessible ways to provide end-user type documentation than via api. It does mean of course that unless a way is found to incorporate this into the rustdoc it wouldn't show up in docs.rs which I admit is unfortunate.

**Comment by alamb** [comment]
> > @Omega359 I'm thinking if we can build the same doc from using rustdoc or rust attributes 🤔
> 
> Absolutely we could, and I actually toyed with rustdoc approach at first. My main concern with that is that I envision this is useful outside of just the website documentation and for that I would believe we want the docs to be as easily accessible as possible. I can't think of more accessible ways to provide end-user type documentation than via api. It does mean of course that unless a way is found to incorporate this into the rustdoc it wouldn't show up in docs.rs which I admit is unfortunate.

Maybe we can add something to the rust docs (via macro or something) that points do the website version. 

Or we could perhaps make a similar script that would update the inlined rust documentation too (that might be getting too fancy 🤔 )

**Pull request merged**
