### PR TITLE
Introduce `resources_err!` error macro

### PR DESCRIPTION
**Pull request by comphead**
## Which issue does this PR close?

Closes #.
Related to https://github.com/apache/datafusion/issues/7360

## Rationale for this change

Expand error macros series in DataFusion to include a `ResourcesExhausted` error

### CODE REVIEW

**Comment by Weijun-H** [comment]
It would be better to replace the following but also be done on a follow-on.

https://github.com/apache/arrow-datafusion/blob/37428bb2034abc1aba5d4cd52cf8f2885623bada/datafusion/physical-plan/src/aggregates/mod.rs#L1881-L1884

https://github.com/apache/arrow-datafusion/blob/37428bb2034abc1aba5d4cd52cf8f2885623bada/datafusion/physical-plan/src/aggregates/row_hash.rs#L606-L610

**Review by Weijun-H — APPROVED** [review]
LGTM! Thanks @comphead  👍

**Review by alamb — APPROVED** [review]
Thanks @comphead  and thanks @Weijun-H  for the review and suggestions

**Comment by comphead** [comment]
Thanks folks for the review

**Pull request merged**
