### PR TITLE
Crypto Function Migration

### LINKED ISSUE #12828: Migrate documentation for all crypto functions from scalar_functions.md to code
### Is your feature request related to a problem or challenge?

As part of https://github.com/apache/datafusion/issues/12740 this ticket is to migrate all the existing documentation for the above named functions from the static documentation to code and to remove them from the static file. 

Here is the current static content:
* doc source: https://github.com/apache/datafusion/blob/main/docs/source/user-guide/sql/scalar_functions.md
* rendered: https://datafusion.apache.org/user-guide/sql/scalar_functions.html
* Code source: https://github.com/apache/datafusion/tree/main/datafusion/functions/src/crypto

Need Functions:
(see source)

### Describe the solution you'd like

One (or more) PRs that
1. port the documentation for the above named functions from the static docs to code
2. Bonus points:  add sql examples should be added for all functions
3. Remove the documentation from the static docs

Here are some example PRs of doing this:
1. https://github.com/apache/datafusion/pull/12775 from @Omega359 
3. https://github.com/apache/datafusion/pull/12742

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jonathanc-n**
## Which issue does this PR close?

Closes #12828.

## Rationale for this change
Migration of crypto functions

## What changes are included in this PR?
Migrated crypto functions from scalar.md to new generated format

### CODE REVIEW

**Comment by jonathanc-n** [comment]
@Omega359 Does this look correct? That was so cool btw, running the script and then everything appearing

**Comment by alamb** [comment]
wasmtest Ci failure has been fixed in https://github.com/apache/datafusion/pull/12844

**Comment by alamb** [comment]
close/reopen to retrigger CI

**Review by Omega359 — APPROVED** [review]
LGTM - thanks for the help in migrating the docs! ❤️

**Review by alamb — APPROVED** [review]
Thank you @jonathanc-n  and @Omega359  

The power of the community at work!

**Pull request merged**
