### PR TITLE
Add user_defined_sql_planners(..) to FunctionRegistry

### LINKED ISSUE #11294: Add supporting functions for user defined sql planners to FunctionRegistry
### Is your feature request related to a problem or challenge?

Currently with the function registry trait you can register a user defined sql planner to the FunctionRegistry but there is no ability to get a list of registered user defined sql planners.

### Describe the solution you'd like

`fn user_defined_sql_planners(&self) -> Vec<Arc<dyn UserDefinedSQLPlanner>>`

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Omega359**
## Which issue does this PR close?

Closes #11294

## Rationale for this change

Adding the ability to retrieve the list of registered user defined sql functions.

## What changes are included in this PR?

Code, test.

## Are these changes tested?

A simple test was added to verify api returns something.

## Are there any user-facing changes?

FunctionRegistry trait was ammended.

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Makes sense to me -- thank you @Omega359 

However what do you think about using the name `expr_planners` rather than `user_defined_sql_planner`s https://github.com/apache/datafusion/issues/11304 ?

I realize this PR is consistent with the current names, but as the API is expanding so it is probably a good ideae to ensure the nemes are good

**Comment by Omega359** [comment]
I'm ok with that as long as the register function neme (and I suppose deregister in the future) mirrors the naming scheme. I can file a followup issue to have that renamed.

**Comment by Omega359** [comment]
Rename update pushed.

**Review by alamb — APPROVED** [review]
Thank you @Omega359

**Pull request merged**
