### PR TITLE
Better Cast name for display

### LINKED ISSUE #10274: Incorrect type display for CAST
### Describe the bug

The type for CAST is not correct when using datafusion-cli

### To Reproduce

DataFusion CLI v37.1.0
> SELECT CAST(2 AS INTEGER);
+----------+
| Int64(2) |
+----------+
| 2        |
+----------+
1 row(s) fetched. 
Elapsed 0.027 seconds.

> SELECT CAST(2 AS DOUBLE);
+----------+
| Int64(2) |
+----------+
| 2.0      |
+----------+
1 row(s) fetched. 
Elapsed 0.005 seconds.

> SELECT arrow_typeof(CAST(2 AS DOUBLE));
+------------------------+
| arrow_typeof(Int64(2)) |
+------------------------+
| Float64                |
+------------------------+
1 row(s) fetched. 
Elapsed 0.008 seconds.

### Expected behavior

_No response_

### Additional context

I'm finding what's wrong with it. I think it's not an issue from datafusion-cli but from the CAST itself. 🤔

### PR DESCRIPTION
**Pull request by yyy1000**
## Which issue does this PR close?

Closes #10274 .

### CODE REVIEW

**Comment by yyy1000** [comment]
I encountered a problem for `type_coercion` and need help🥲
Here `TypeCoercion` would rewrite an `Expr` thus brings a 'Cast',  and the name for `Cast` would not just be the expr name in the `Cast` in this PR, thus `rewrite_preserving_name` will introduce an `Alias`, which is not expected.
https://github.com/apache/datafusion/blob/b41ef20c5dad7bdd674e3cc5f35a9c99efae676c/datafusion/optimizer/src/analyzer/type_coercion.rs#L102-L116

**Comment by jayzhan211** [comment]
I think we should change the `display_name` not `create_name`, as the commented said, name for casting should preserve

**Comment by alamb** [comment]
Looks like this one has some test failures to review before it is ready for review

**Comment by yyy1000** [comment]
I encountered an issue: the plan's schema would change during rewrite stage.👀
In 
> explain verbose SELECT CAST(2 AS INTEGER);

```
+----------------------------------------------------------------------------+--------------------------------------------------------------------------------------+
| plan_type                                                                  | plan                                                                                 |
+----------------------------------------------------------------------------+--------------------------------------------------------------------------------------+
| initial_logical_plan                                                       | Projection: CAST(Int64(2) AS Int32)                                                  |
|                                                                            |   EmptyRelation                                                                      |
| logical_plan after apply_function_rewrites                                 | SAME TEXT AS ABOVE                                                                   |
| logical_plan after inline_table_scan                                       | SAME TEXT AS ABOVE                                                                   |
| logical_plan after type_coercion                                           | SAME TEXT AS ABOVE                                                                   |
| logical_plan after count_wildcard_rule                                     | SAME TEXT AS ABOVE                                                                   |
| analyzed_logical_plan                                                      | SAME TEXT AS ABOVE                                                                   |
| logical_plan after eliminate_nested_union                                  | SAME TEXT AS ABOVE                                                                   |
| logical_plan after simplify_expressions                                    | Projection: Int32(2) AS Int64(2)                                                     |
|                                                                            |   EmptyRelation                                                                      |
| logical_plan after unwrap_cast_in_comparison                               | SAME TEXT AS ABOVE                                                                   |
| logical_plan after replace_distinct_aggregate                              | SAME TEXT AS ABOVE                                                                   |
| logical_plan after eliminate_join                                          | SAME TEXT AS ABOVE                                                                   |
| logical_plan after decorrelate_predicate_subquery                          | SAME TEXT AS ABOVE                                                                   |
| logical_plan after scalar_subquery_to_join                                 | SAME TEXT AS ABOVE                                                                   |
| logical_plan after extract_equijoin_predicate                              | SAME TEXT AS ABOVE                                                                   |
| logical_plan after simplify_expressions                                    | SAME TEXT AS ABOVE                                                                   |
| logical_plan after rewrite_disjunctive_predicate                           | SAME TEXT AS ABOVE                                                                   |
| logical_plan after eliminate_duplicated_expr                               | SAME TEXT AS ABOVE                                                                   |
| logical_plan after eliminate_filter                                        | SAME TEXT AS ABOVE                                                                   |
| logical_plan after eliminate_cross_join                                    | SAME TEXT AS ABOVE                                                                   |
| logical_plan after Optimizer rule 'common_sub_expression_eliminate' failed | Schema error: No field named "CAST(Int64(2) AS Int32)". Valid fields are "Int64(2)". |
+----------------------------------------------------------------------------+--------------------------------------------------------------------------------------+
20 row(s) fetched. 
Elapsed 0.008 seconds.
```

After `simplify_expressions`, `ConstEvaluator` will rewrite the `Cast` to an `Alias` to `ScalarValue`, and the name for the `Alias` is different from the Field name in the original schema (Because in the past the Cast's name is just the expr, which is the same as the Alias's name, but now it's not.

I will dive into related code but it may take some time. :) I'm not so familiar with related code base but I will try to learn it.

**Pull request closed without merging**
