### PR TITLE
fix bugs for explain supporting non-correlated subquery

### LINKED ISSUE #5265: Some In/Exists Subqueries will generate wrong PhysicalPlan
**Describe the bug**

Datafusion can't execute non-correlated subquery now, like in/exists.
So these queries should return `NotImplemented("Physical plan does not support logical expression In/Exists` error. But currently the filter will be pushdown to the TableScan.
```sql
> explain select * from t1 where exists(select 1 from t2 where t2.t2_id > 0);
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                                        |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: t1.t1_id, t1.t1_name, t1.t1_int                                                                                                                 |
|               |   TableScan: t1 projection=[t1_id, t1_name, t1_int], full_filters=[EXISTS (<subquery>)]                                                                     |
|               |     Subquery:                                                                                                                                               |
|               |       Projection: Int64(1)                                                                                                                                  |
|               |         Filter: CAST(t2.t2_id AS Int64) > Int64(0)                                                                                                          |
|               |           TableScan: t2                                                                                                                                     |
| physical_plan | ProjectionExec: expr=[t1_id@0 as t1_id, t1_name@1 as t1_name, t1_int@2 as t1_int]                                                                           |
|               |   CsvExec: files={1 group: [[home/work/tools/datafusion-test-data/join-context/t1.csv]]}, has_header=false, limit=None, projection=[t1_id, t1_name, t1_int] |
|               |                                                                                                                                                             |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

For the above query, the subquery filter will be  lost in the final `physical_plan`.

**To Reproduce**
As above.

**Expected behavior**
The query should return `NotImplemented("Physical plan does not support logical expression In/Exists` error.

**Additional context**

### PR DESCRIPTION
**Pull request by Lordworms**
## Which issue does this PR close?

Closes #5265

### CODE REVIEW

**Review by Dandandan — APPROVED** [review]

**Comment by alamb** [comment]
I am sorry @Lordworms and @Dandandan  - I messed up this PR -- I accidentally force pushed the branch without any code commits and that caused github to close the PR 😢 

This commit needs to be cherry-picked and then the branch repushed

```shell
git cherry-pick b0758c059
```

**Comment by alamb** [comment]
What I was trying to do was avoid the changes in the tests

Rather than percolating the error out and failing the `EXPLAIN` what would you think about potentially changing the Explain plan so the physical plan result was the error message instead?

**Comment by Lordworms** [comment]
> also open a new PR with the same change

I think that would be better, I'll cherry-pick the commits, Thanks a lot.

**Comment by alamb** [comment]
> > also open a new PR with the same change
> 
> I think that would be better, Thanks a lot. I'll change it into the error message.

Again I am really sorry. 

To confirm, you plan to open another PR, or would you like me to do so?

**Comment by Lordworms** [comment]
> > > also open a new PR with the same change
> > 
> > 
> > I think that would be better, Thanks a lot. I'll change it into the error message.
> 
> Again I am really sorry.

Don't worry, it is fine :)

> 
> To confirm, you plan to open another PR, or would you like me to do so?

I can do that

**Comment by alamb** [comment]
New PR: https://github.com/apache/datafusion/pull/13210

**Pull request closed without merging**
