### PR TITLE
Backport "Provide field and schema metadata missing on cross joins, and union with null fields" (#12729)

### PR DESCRIPTION
**Pull request by matthewmturner**
## Which issue does this PR close?

Part of #12813 . Applies fixes from https://github.com/apache/datafusion/pull/12729 to DataFusion version 42

### CODE REVIEW

**Comment by matthewmturner** [comment]
@alamb @Xuanwo FYI

**Review by alamb — APPROVED** [review]
Thank you @matthewmturner  -- I updated the title of this PR to be a bit more descriptive when it shows up in the release notes

**Comment by alamb** [comment]
FYI @wiedld

**Comment by alamb** [comment]
For the CI failures, we may need to backport this PR as well: https://github.com/apache/datafusion/pull/12724

I will give it a go

**Comment by alamb** [comment]
I backported the fixes for CI: https://github.com/apache/datafusion/pull/12977

close/reopen to trigger CI on this PR

**Comment by matthewmturner** [comment]
i am looking into the CI failure

**Comment by alamb** [comment]
(btw I found using `git cherry-pick` to be a more foolproof way to backport commits -- git often does most of the work for you

**Pull request merged**
