### PR TITLE
fix: nested loop join requires outer table to be a FusedStream

### LINKED ISSUE #12187: Left/Full join of the NestedLoopJoin requires the RHS(outer table) to be a FusedStream
### Describe the bug

According to the [code](https://github.com/apache/datafusion/blob/main/datafusion/physical-plan/src/joins/nested_loop_join.rs#L474), when the outer table returns `None` for the first time, the `NestedLoopJoinStream` may return `Some(RecordBatch)` to produce the result for the unmatched rows. Therefore, the `NestedLoopJoinStream` is not exhausted and will be polled again. However, the next poll will also poll the outer_table, when the outer_table does not support the [FusedStream](https://docs.rs/futures/latest/futures/prelude/stream/trait.FusedStream.html), it may panic.

To fix the bug, we could require the [execute](https://docs.rs/datafusion/latest/datafusion/physical_plan/trait.ExecutionPlan.html#tymethod.execute) method returns a `FusedStream` or add a wrapper for the outer_table

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by YjyJeff**
## Which issue does this PR close?

Closes #12187 

## Are these changes tested?
Yes

## Are there any user-facing changes?

No

### CODE REVIEW

**Review by crepererum — COMMENTED** [review]
Is this bug visible/reproducible somehow? If so, could you add a regression test?

**Comment by YjyJeff** [comment]
> Is this bug visible/reproducible somehow? If so, could you add a regression test?

@crepererum  This bug is triggered by our customized `TableScan` operator that does not support `FusedStream` contract. In our implementation, when the stream is finished, calling the `poll_next` method again will cause panic.  

It is simple to mimic the above situation. Firstly, modify the [MemoryStream](https://github.com/apache/datafusion/blob/main/datafusion/physical-plan/src/memory.rs#L281) such that it does not support `FusedStream` contract with following code: 

```rust
    fn poll_next(
        mut self: std::pin::Pin<&mut Self>,
        _: &mut Context<'_>,
    ) -> Poll<Option<Self::Item>> {
        Poll::Ready(if self.index < self.data.len() {
            self.index += 1;
            let batch = &self.data[self.index - 1];

            // return just the columns requested
            let batch = match self.projection.as_ref() {
                Some(columns) => batch.project(columns)?,
                None => batch.clone(),
            };

            Some(Ok(batch))
        } else if self.index == self.data.len() {
            self.index += 1;
            None
        } else {
            panic!("Exhausted stream is polled again")
        })
    }
```
Secondly, run the `datafusion-cli` binary with following sqls:
```SQL
CREATE TABLE wtf AS VALUES (4, 'arrow'), (99, 'datafusion');

select t0.column1, t1.column1, t0.column2, t1.column2 from wtf t0 left join wtf t1 on t0.column1 > t1.column1;
```
Then, we will hit the `panic` statement. 

Currently, the `ExecutionPlan` trait only requires the `execute` method to return the struct that implements the `Stream` trait. According to the definition of the [poll_next](https://docs.rs/futures/latest/futures/stream/trait.Stream.html#tymethod.poll_next) method, panic can happens when polling the exhausted stream

**Comment by crepererum** [comment]
I think we have roughly the following paths forward here:

- just fix this issue here (w/ or w/o regression test)
- do NOT require `FusedStream`: we could invest in some tests that patch the physical plan to replace all streams with ones that panic if they are polled after the end (e.g. enforce NOT `FusedStream`)
- update the entire stack to require `FusedStream` (requires additional flags/state in a few places, so potentially costly)

**Review by alamb — APPROVED** [review]
Thank you @crepererum  and @YjyJeff  -- I think this PR would be ok to merge. 

> just fix this issue here (w/ or w/o regression test)

I would prefer "fix the issue here with a regression test"

The reason I suggest a regression test is that otherwise this code may very well get lost in a future refactoring -- without regression tests for coverage we wouldn't know if this happened

Do you think you can add such a test @YjyJeff ?

**Comment by alamb** [comment]
I will wait a few more days to merge this PR to see if @YjyJeff can help add a regression test

**Comment by alamb** [comment]
Merging this to get it into 42 

It would be great to get a test for this @YjyJeff  otherwise it is likely a regression will creep in. Let's try and do that as a follow on PR

**Pull request merged**
