### PR TITLE
Print undocumented functions to console while generating docs

### PR DESCRIPTION
**Pull request by alamb**
## Which issue does this PR close?

Part of https://github.com/apache/datafusion/issues/12740

First part of https://github.com/apache/datafusion/issues/12872

## Rationale for this change

Eventually I would like to ensure that all functions have documentation. Now that we have the automated documentation builder in place, it is possible to see what is missing.

## What changes are included in this PR?

As first step, update the print docs script to print out the list of functions that are not documented. As a follow on PR I will make this an error once we have all functions documented

## Are these changes tested?

I tested them manually. Here is what it looks like:

```shell
INFO: The following functions do not have documentation:
  - regr_avgy
  - regr_sxx
  - regr_slope
  - regr_r2
  - regr_count
  - regr_avgx
  - regr_syy
  - regr_intercept
  - regr_sxy
...
```

Here is what it looked like before

```shell
(venv) andrewlamb@Andrews-MacBook-Pro-2:~/Software/datafusion$ ./dev/update_function_docs.sh
/Users/andrewlamb/Software/datafusion
Inserting header
Running CLI and inserting aggregate function docs table
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/print_functions_docs aggregate`
Running prettier
docs/source/user-guide/sql/aggregate_functions_new.md 58ms
'docs/source/user-guide/sql/aggregate_functions_new.md' successfully updated!
Inserting header
Running CLI and inserting scalar function docs table
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/print_functions_docs scalar`
Running prettier
docs/source/user-guide/sql/scalar_functions_new.md 93ms
'docs/source/user-guide/sql/scalar_functions_new.md' successfully updated!
Inserting header
Running CLI and inserting window function docs table
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/print_functions_docs window`
Running prettier
docs/source/user-guide/sql/window_functions_new.md 23ms
'docs/source/user-guide/sql/window_functions_new.md' successfully updated!
```

### CODE REVIEW

**Comment by alamb** [comment]
FYI @Omega359 and @jonathanc-n

**Review by Omega359 — APPROVED** [review]
LGTM - thanks @alamb

**Comment by jonathanc-n** [comment]
this LGTM thanks for the help @alamb

**Review by findepi — APPROVED** [review]

**Comment by alamb** [comment]
Thank you everyone for the review

**Pull request merged**
