### PR TITLE
Enable needless_pass_by_value clippy lint

### PR DESCRIPTION
**Pull request by findepi**
Relates to https://github.com/apache/datafusion/pull/12197#issuecomment-2314799720

### CODE REVIEW

**Comment by findepi** [comment]
draft -- waits for https://github.com/apache/datafusion/pull/12242 & https://github.com/apache/datafusion/pull/12207

**Comment by findepi** [comment]
> Relates to [#12197 (comment)](https://github.com/apache/datafusion/pull/12197#issuecomment-2314799720)

cc @crepererum

**Comment by crepererum** [comment]
could you try to factor out the API changes into separate PRs? This would make the reviews and the changelog generation a bit easier.

**Comment by findepi** [comment]
> could you try to factor out the API changes into separate PRs? This would make the reviews and the changelog generation a bit easier.

good call!

extracted these for now
- https://github.com/apache/datafusion/pull/12260
- https://github.com/apache/datafusion/pull/12261
- https://github.com/apache/datafusion/pull/12262

**Pull request closed without merging**
