### PR TITLE
CI: Windows test execution time

### PR DESCRIPTION
**Pull request by comphead**
## Which issue does this PR close?

Related to https://github.com/apache/datafusion/issues/13726
Closes #.

## Rationale for this change

Test Windows compilation time improvements

### CODE REVIEW

**Comment by comphead** [comment]
```
Executed "map.slt". Took 460.5636141s
Executed "window.slt". Took 217.240136s
Executed "struct.slt". Took 1316.049712s
Executed "array.slt". Took 2407.7054095s
```

Thats really weird, a simple array SLT takes 40 mins

**Comment by korowa** [comment]
@comphead disregarding build arguments, which may affect build performance, there seems to be a known [issue](https://github.com/actions/runner-images/issues/7320) with IO on windows runners which is noticeably slower than linux/mac ones. From comments to that issue it looks like some projects are able to get performance benefit using DevDrive, so it may be a different perspective to look at this problem from.

**Comment by comphead** [comment]
> @comphead disregarding build arguments, which may affect build performance, there seems to be a known [issue](https://github.com/actions/runner-images/issues/7320) with IO on windows runners which is noticeably slower than linux/mac ones. From comments to that issue it looks like some projects are able to get performance benefit using DevDrive, so it may be a different perspective to look at this problem from.

Thanks @korowa for the hint I was playing with lots of combination including different Windows images but nothing seems to work.

**Comment by comphead** [comment]
Some projects give up rust testing on Windows like https://github.com/DataDog/orchestrion/pull/415

@alamb wondering should we pause the Windows flow temporarily? The build time is incredibly slow and we holding GH resources for way longer time

**Comment by alamb** [comment]
Another thing that would benefit the project as a whole is to reduce build time.

One thing I noticed a while ago is that each binary built (e.g. every example) was around 100MB

I was thinking that we could reduce / conslidate the number of examples / binaries built which would speed up all runners (not just Windows)

For example consolidating https://github.com/apache/datafusion/blob/main/datafusion-examples/examples/regexp.rs and other examples of using functions into `dataframe_api.rs` might be a good win

**Comment by comphead** [comment]
Closing it as there is no any progress after all the experiments

**Pull request closed without merging**
