### PR TITLE
Implement TPCH substrait integration test, support tpch_13, tpch_14,16

### PR DESCRIPTION
**Pull request by Lordworms**
part of #10710 

## Which issue does this PR close?

Closes #.

### CODE REVIEW

**Comment by Lordworms** [comment]
query 15 is missing. I'll add the missing queries once I have done the existing ones.

**Review by alamb — APPROVED** [review]
Thanks @Lordworms 🙏 

I think @Blizzara  added a clearner way to setup the contexts in  https://github.com/apache/datafusion/pull/11396

Would it be possible to use that new pattern in this PR too?

**Comment by Lordworms** [comment]
> Thanks @Lordworms 🙏
> 
> I think @Blizzara added a clearner way to setup the contexts in #11396
> 
> Would it be possible to use that new pattern in this PR too?

Sure

**Review by Blizzara — APPROVED** [review]
Nice, thanks!

**Comment by alamb** [comment]
Thanks again @Blizzara  and @Lordworms 🚀

**Pull request merged**
