### PR TITLE
chore: Consolidate Example: simplify_udwf_expression.rs into advanced_udwf.rs

### LINKED ISSUE #13843: Consolidate Example: simplify_udwf_expression.rs into advanced_udwf.rs #13842
### Is your feature request related to a problem or challenge?

- Part of https://github.com/apache/datafusion/issues/11172

The large number of small examples in DataFusion leads to multiple problems:
- Unnecessarily large amounts of temporary disk space (each example binary takes 100+ MB)
- Larger `cargo t` time (each binary must be linked / created)
- Makes it harder to find the relevant examples

Thus I think the fewer examples we have the 
1. faster our dev experience will be 
2. easier it will be to find the relevant examples

### Describe the solution you'd like

- Consolidate the contents of the window function example [simplify_udwf_expression](https://github.com/apache/datafusion/blob/main/datafusion-examples/examples/simplify_udwf_expression.rs)
- Into [advanced_udwf.rs](https://github.com/apache/datafusion/blob/main/datafusion-examples/examples/advanced_udwf.rs)

Then update the readme page: 
- https://github.com/apache/datafusion/blob/main/datafusion-examples/README.md

### Describe alternatives you've considered

_No response_

### Additional context

I think this is a good first issue as the task is straightforward and doesn't require deep understanding of the DataFusion codebase

### PR DESCRIPTION
**Pull request by xarus01**
## Which issue does this PR close?

Closes #13843.

## Rationale for this change

Part of #11172

## What changes are included in this PR?

* Consolidate contents of `simplify_udwf_expression.rs` into `advanced_udwf.rs`.
* Update docstring referencing `simplify_udwf_expression.rs`.

## Are these changes tested?

Yes.

## Are there any user-facing changes?

Updated docstring in `datafusion/expr/src/udwf.rs`.

### CODE REVIEW

**Comment by xarus01** [comment]
@alamb - mentioning per [contribution guide](https://datafusion.apache.org/contributor-guide/index.html#pull-request-overview). Please trigger the CI tasks.

**Review by alamb — APPROVED** [review]
Thank you @xarus01  -- this looks great 🙏  -

Another step towards getting the code in better shape 🚀

**Review by alamb — COMMENTED** [review]
I double checked and it seems this example isn't even listed in the [README](https://github.com/apache/datafusion/blob/main/datafusion-examples/README.md) (so there is no need to update that)

**Comment by alamb** [comment]
Thanks again @xarus01

**Pull request merged**
